export type CityTier = "metro" | "tier1" | "tier2";

export interface CityData {
  slug: string;
  name: string;
  state: string;
  tier: CityTier;
  areas: string[];
  repairMarkets: string[];
  priceIndex: number;
  population: string;
  techCount: number;
  reviewCount: number;
  avgRating: number;
  responseMinutes: string;
  localIntro: string;
  nearbyCity?: string;
}

export const CITIES: CityData[] = [
  // METRO
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    tier: "metro",
    areas: ["HITEC City", "Banjara Hills", "Jubilee Hills", "Kondapur", "Gachibowli", "Madhapur", "Ameerpet", "Kukatpally"],
    repairMarkets: ["Abids Electronics Market", "Secunderabad Clock Tower Market", "SR Nagar Computer Market"],
    priceIndex: 1.0,
    population: "1.0 crore",
    techCount: 140,
    reviewCount: 312,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "From the tech corridors of HITEC City to the bustling lanes near Charminar, LocalTech certified technicians reach you across Hyderabad — typically within 40 minutes. Whether you work in Gachibowli's glass towers or live in the old-city bylanes, we come to you.",
  },
  {
    slug: "bangalore",
    name: "Bangalore",
    state: "Karnataka",
    tier: "metro",
    areas: ["Koramangala", "Indiranagar", "Whitefield", "HSR Layout", "Jayanagar", "Electronic City", "Marathahalli", "BTM Layout"],
    repairMarkets: ["SP Road Electronics", "Chickpet Electronics", "Nehru Street Shivajinagar"],
    priceIndex: 1.0,
    population: "1.4 crore",
    techCount: 155,
    reviewCount: 387,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Bangalore runs on screens — from laptop-laden cafes in Koramangala to the startup offices packed along ORR. When your device breaks mid-sprint, LocalTech dispatches a verified technician to your desk or doorstep, often before your next standup.",
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    tier: "metro",
    areas: ["Andheri", "Bandra", "Thane", "Navi Mumbai", "Borivali", "Dadar", "Kurla", "Malad"],
    repairMarkets: ["Lamington Road Electronics", "Heera Panna Market", "Ghatkopar Electronics Market"],
    priceIndex: 1.0,
    population: "2.0 crore",
    techCount: 170,
    reviewCount: 401,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "In a city that never stops — from Andheri's offices to Thane's apartments — a broken phone costs you more than money. LocalTech same-day repair serves all of Mumbai with no traffic excuses; our technicians know every shortcut.",
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    tier: "metro",
    areas: ["Connaught Place", "Lajpat Nagar", "Dwarka", "Rohini", "Janakpuri", "Saket", "Noida Extension", "Greater Noida"],
    repairMarkets: ["Nehru Place Electronics", "Lajpat Nagar Market", "Palika Bazaar"],
    priceIndex: 1.0,
    population: "1.9 crore",
    techCount: 160,
    reviewCount: 375,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Delhi's repair ecosystem stretches from Nehru Place's wholesale shops to the GK boutiques — but price transparency is rare. LocalTech brings fixed, upfront pricing and background-verified technicians to your door, from Dwarka to Noida in a single platform.",
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    tier: "metro",
    areas: ["Anna Nagar", "T. Nagar", "Velachery", "Porur", "Adyar", "Chromepet", "Tambaram", "OMR"],
    repairMarkets: ["Ritchie Street Electronics", "Anna Salai Market", "Parrys Corner"],
    priceIndex: 1.0,
    population: "1.1 crore",
    techCount: 130,
    reviewCount: 295,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "From the IT corridors along OMR to the dense residential blocks of Anna Nagar, Chennai has one of India's highest smartphone ownership rates per household. LocalTech connects you with certified technicians who know the city's traffic patterns and reach you fast.",
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    tier: "metro",
    areas: ["Salt Lake", "New Town", "Park Street", "Howrah", "Dumdum", "Behala", "Tollygunge", "Jadavpur"],
    repairMarkets: ["Chandni Chowk Electronics", "Esplanade Market", "Hatibagan Market"],
    priceIndex: 1.0,
    population: "1.5 crore",
    techCount: 120,
    reviewCount: 267,
    avgRating: 4.7,
    responseMinutes: "35–45",
    localIntro: "Kolkata's New Town tech hubs and the old-school electronics lanes of Chandni Chowk sit 40 minutes apart, but repair quality varies wildly. LocalTech's vetted technicians bring consistent, priced service whether you're in Salt Lake Sector V or Howrah.",
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    tier: "metro",
    areas: ["Kothrud", "Hinjewadi", "Viman Nagar", "Hadapsar", "Kalyani Nagar", "FC Road", "Baner", "Wakad"],
    repairMarkets: ["Budhwar Peth Electronics", "Camp Market", "FC Road IT Hub"],
    priceIndex: 1.0,
    population: "73 lakh",
    techCount: 115,
    reviewCount: 248,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Pune's student neighbourhoods near FC Road and the IT parks of Hinjewadi both demand fast, reliable device repair. LocalTech covers all of Pune's rapidly growing boundaries — from Wakad to Hadapsar — with technicians who've passed a practical skills test.",
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    tier: "metro",
    areas: ["CG Road", "Navrangpura", "SG Highway", "Satellite", "Bopal", "Prahlad Nagar", "Vastrapur", "Maninagar"],
    repairMarkets: ["Manek Chowk Electronics", "Relief Road Market", "CG Road Tech Market"],
    priceIndex: 1.0,
    population: "82 lakh",
    techCount: 110,
    reviewCount: 231,
    avgRating: 4.7,
    responseMinutes: "35–45",
    localIntro: "Ahmedabad's CG Road corridor and the spreading tech districts around SG Highway have a rapidly growing device-dependent workforce. LocalTech brings certified repair service to your home or office — from the old city near Manek Chowk to the new campuses in GIFT City.",
  },
  // TIER 1
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    tier: "tier1",
    areas: ["Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Mansarovar", "Jagatpura", "Tonk Road", "Bani Park", "Raja Park"],
    repairMarkets: ["Nehru Bazaar Electronics", "Ashok Nagar Market", "MI Road Tech Market"],
    priceIndex: 0.9,
    population: "40 lakh",
    techCount: 52,
    reviewCount: 187,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Behind Jaipur's Pink City walls, a new generation of device users in Malviya Nagar and Vaishali Nagar need repair services that match their pace. LocalTech brings fixed-price transparency to a market often dominated by Nehru Bazaar's bargain shops.",
    nearbyCity: "delhi",
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    tier: "tier1",
    areas: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar", "Alambagh", "Vikas Nagar", "Charbagh", "Rajajipuram"],
    repairMarkets: ["Sadar Electronics Market", "Aminabad Market", "Hazratganj Tech Hub"],
    priceIndex: 0.9,
    population: "36 lakh",
    techCount: 48,
    reviewCount: 175,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Lucknow's Gomti Nagar IT corridor and the old-city lanes near Aminabad both have device users looking for honest repair. LocalTech's technicians navigate the city's famous traffic to reach you — bringing a written estimate before touching your phone.",
    nearbyCity: "delhi",
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    tier: "tier1",
    areas: ["Kakkanad", "Edapally", "MG Road", "Aluva", "Thrikkakara", "Marine Drive", "Panampilly Nagar", "Vyttila"],
    repairMarkets: ["Broadway Market", "MG Road Electronics", "Edapally Electronics Hub"],
    priceIndex: 0.9,
    population: "22 lakh",
    techCount: 45,
    reviewCount: 168,
    avgRating: 4.8,
    responseMinutes: "40–55",
    localIntro: "Kochi's Kakkanad technopark hosts thousands of IT professionals who can't afford device downtime. LocalTech ensures a vetted technician reaches you on Infopark campus or your Marine Drive apartment, usually within the hour.",
    nearbyCity: "thiruvananthapuram",
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Punjab/Haryana",
    tier: "tier1",
    areas: ["Sector 17", "Sector 22", "Sector 35", "Panchkula", "Mohali", "Zirakpur", "Manimajra", "Sector 43"],
    repairMarkets: ["Sector 22 Electronics", "Sector 17 Market", "Mohali Phase 7 Market"],
    priceIndex: 0.9,
    population: "12 lakh",
    techCount: 38,
    reviewCount: 152,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Chandigarh's planned grid makes doorstep service genuinely fast — our technicians use sector addresses to find you in minutes, not hours. From Sector 17's commercial heart to Mohali's IT Park, LocalTech covers the entire tricity.",
    nearbyCity: "amritsar",
  },
  {
    slug: "coimbatore",
    name: "Coimbatore",
    state: "Tamil Nadu",
    tier: "tier1",
    areas: ["RS Puram", "Gandhipuram", "Peelamedu", "Saibaba Colony", "Singanallur", "Kovai Pudur", "Race Course", "Vadavalli"],
    repairMarkets: ["Big Bazaar Street Electronics", "Oppanakara Street Market", "DB Road Tech Market"],
    priceIndex: 0.9,
    population: "21 lakh",
    techCount: 42,
    reviewCount: 161,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Coimbatore's textile and engineering industries run on mobile connectivity, making fast repair essential. LocalTech serves RS Puram's offices and Peelamedu's student hubs equally — with transparent pricing that beats the walk-in shops on Oppanakara Street.",
    nearbyCity: "chennai",
  },
  {
    slug: "bhopal",
    name: "Bhopal",
    state: "Madhya Pradesh",
    tier: "tier1",
    areas: ["MP Nagar", "Arera Colony", "New Market", "Hoshangabad Road", "Kolar", "Lalghati", "Karond", "BHEL"],
    repairMarkets: ["New Market Electronics", "DB Mall Tech Hub", "MP Nagar Computer Market"],
    priceIndex: 0.9,
    population: "24 lakh",
    techCount: 40,
    reviewCount: 158,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Bhopal's dual urban core — old city around New Market and the new zones along Hoshangabad Road — spans a wide geography. LocalTech's technicians are stationed across both sides so your wait time stays short wherever you are.",
    nearbyCity: "indore",
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    tier: "tier1",
    areas: ["Vijay Nagar", "Palasia", "MG Road", "Rau", "Nipania", "Scheme 54", "LIG Colony", "Lasudia"],
    repairMarkets: ["Electronics Complex Palasia", "MG Road Market", "Malhar Mega Mall Tech Street"],
    priceIndex: 0.9,
    population: "35 lakh",
    techCount: 50,
    reviewCount: 179,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Indore ranked India's cleanest city for six straight years — and its smartphone repair market matches that appetite for quality. LocalTech brings the same standard to your device: verified technicians, clean workmanship, upfront pricing, no mess left behind.",
    nearbyCity: "bhopal",
  },
  {
    slug: "nagpur",
    name: "Nagpur",
    state: "Maharashtra",
    tier: "tier1",
    areas: ["Dharampeth", "Sitabuldi", "Laxmi Nagar", "Nagpur University Road", "Wardha Road", "Amravati Road", "Hingna", "Wadi"],
    repairMarkets: ["Sitabuldi Market", "Dharampeth Electronics", "Lokmat Square Tech Market"],
    priceIndex: 0.9,
    population: "27 lakh",
    techCount: 44,
    reviewCount: 163,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "At the geographic centre of India, Nagpur's MIHAN aerospace and IT zone is growing fast — and its device users expect metro-class repair. LocalTech delivers that with verified technicians across Dharampeth, Laxmi Nagar, and the new Wardha Road development.",
    nearbyCity: "pune",
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    tier: "tier1",
    areas: ["Dwaraka Nagar", "MVP Colony", "Rushikonda", "Gajuwaka", "Seethammadhara", "Waltair", "NAD Junction", "Steel Plant"],
    repairMarkets: ["Dwaraka Nagar Electronics", "RTC Complex Market", "MVP Colony Tech Street"],
    priceIndex: 0.9,
    population: "21 lakh",
    techCount: 43,
    reviewCount: 160,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Vizag's navy base, port, and steel plant create a working population that depends on devices around the clock. LocalTech covers the whole city — from the beachfront apartments at Rushikonda to the industrial township near Gajuwaka — with same-day repair.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "surat",
    name: "Surat",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Adajan", "Vesu", "Katargam", "Udhna", "Ring Road", "Althan", "Piplod", "Bhatar Road"],
    repairMarkets: ["Ghod Dod Road Electronics", "Varachha Market", "Katargam Tech Hub"],
    priceIndex: 0.9,
    population: "73 lakh",
    techCount: 55,
    reviewCount: 196,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Surat's diamond and textile traders move fast — they need devices that work. From the busy lanes of Katargam to the new residential towers in Vesu, LocalTech gets a verified technician to your door before your next business call.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "vadodara",
    name: "Vadodara",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Alkapuri", "Manjalpur", "Gorwa", "Fatehgunj", "Race Course", "Gotri", "Karelibaug", "Waghodia Road"],
    repairMarkets: ["Sursagar Electronics", "Sayajigunj Market", "Alkapuri Tech Street"],
    priceIndex: 0.9,
    population: "22 lakh",
    techCount: 40,
    reviewCount: 153,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Vadodara's Alkapuri and the Sayaji Baug neighbourhood have a high density of professionals who need reliable repair without the guesswork of local shops. LocalTech gives you a certified tech with a quoted price, not a verbal estimate that doubles at collection.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "rajkot",
    name: "Rajkot",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Kalawad Road", "University Road", "Jagnath Plot", "Mavdi", "Raiya Road", "150 Feet Ring Road", "Yagnik Road", "Nana Mava"],
    repairMarkets: ["Dhebar Road Electronics", "Gondal Road Market", "Kalavad Road Tech Hub"],
    priceIndex: 0.9,
    population: "19 lakh",
    techCount: 36,
    reviewCount: 144,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Rajkot's SME ecosystem — from auto-parts manufacturers to engineering firms along the 150 Feet Ring Road — relies heavily on mobile connectivity. LocalTech brings dependable, priced repair service across Rajkot without the need to find parking near Dhebar Road shops.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "patna",
    name: "Patna",
    state: "Bihar",
    tier: "tier1",
    areas: ["Boring Road", "Fraser Road", "Bailey Road", "Kankarbagh", "Rajendra Nagar", "Patliputra Colony", "Danapur", "Phulwari"],
    repairMarkets: ["Boring Road Electronics", "Dakbungalow Market", "Fraser Road Tech Market"],
    priceIndex: 0.9,
    population: "25 lakh",
    techCount: 38,
    reviewCount: 148,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Patna's Boring Road has become the city's go-to strip for anything tech, but the repair options are a mixed bag. LocalTech filters that out — you get a screened technician with parts warranty, whether you're in Kankarbagh or Patliputra Colony.",
    nearbyCity: "varanasi",
  },
  {
    slug: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    tier: "tier1",
    areas: ["Harmu Road", "Lalpur", "Doranda", "Bariatu", "Namkum", "Kanke Road", "Argora", "Hinoo"],
    repairMarkets: ["Station Road Electronics", "Main Road Market", "Firayalal Chowk Tech Hub"],
    priceIndex: 0.9,
    population: "14 lakh",
    techCount: 32,
    reviewCount: 136,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Ranchi has grown quickly as a government and commercial hub, but quality device repair has lagged behind. LocalTech is changing that — bringing verified technicians to Lalpur, Harmu Road, and Bariatu with service standards that match what Ranchi's workforce expects.",
    nearbyCity: "patna",
  },
  {
    slug: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    tier: "tier1",
    areas: ["Shankar Nagar", "Pandri", "Devendra Nagar", "Telibandha", "Tikrapara", "GE Road", "Fafadih", "Amanaka"],
    repairMarkets: ["Malviya Road Electronics", "Pandri Market", "Shankar Nagar Tech Street"],
    priceIndex: 0.9,
    population: "13 lakh",
    techCount: 30,
    reviewCount: 130,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "As Chhattisgarh's capital, Raipur is growing fast — new apartments in Devendra Nagar and the commercial bustle on GE Road both need reliable repair service. LocalTech connects you to vetted technicians who come to you, no auto-rickshaw trip to Malviya Road required.",
    nearbyCity: "nagpur",
  },
  // TIER 2
  {
    slug: "vijayawada",
    name: "Vijayawada",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Patamata", "Benz Circle", "Governorpet", "Labbipet", "Suryaraopet", "Moghalrajpuram", "MG Road", "Auto Nagar"],
    repairMarkets: ["Eluru Road Electronics", "Benz Circle Market", "Krishna Lanka Tech Street"],
    priceIndex: 0.8,
    population: "11 lakh",
    techCount: 22,
    reviewCount: 164,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Whether you're near the Prakasam Barrage, picking up electronics in Eluru Road market, or heading home in Patamata, LocalTech brings verified repair service to your door in Vijayawada. Our technicians cross the Benz Circle grid faster than you'd expect.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "guntur",
    name: "Guntur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Brodipet", "Arundelpet", "Nagarampalem", "Kothapet", "Amaravati Road", "Old Town", "Pattabhipuram", "Gorantla"],
    repairMarkets: ["Brodipet Electronics", "Old Town Market", "Amaravati Road Tech Street"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 18,
    reviewCount: 142,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Guntur's pepper and chilli trade built one of Andhra's most commercially active cities — and its professionals run on smartphones. LocalTech serves Brodipet's business hub and the residential quarters of Nagarampalem with same-day mobile repair at published prices.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "warangal",
    name: "Warangal",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hanamkonda", "Kazipet", "NIT Warangal area", "Subedari", "Lashkar Bazaar", "Station Road", "Mulugu Road", "Balasamudram"],
    repairMarkets: ["Station Road Electronics", "Hanamkonda Market", "Subedari Tech Hub"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 17,
    reviewCount: 135,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Warangal's NIT and Kakatiya University bring in thousands of students who need fast, affordable repair. LocalTech bridges that gap — technicians in Hanamkonda and Kazipet with transparent pricing that students and working professionals alike can trust.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Balaji Nagar", "Renigunta Road", "SVIMS Area", "Tilak Road", "Leela Mahal Road", "SV University", "Alipiri", "K.T. Road"],
    repairMarkets: ["Balaji Nagar Electronics", "Car Street Market", "Tilak Road Tech Street"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 15,
    reviewCount: 125,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Tirupati is visited by millions each year, and locals and pilgrims alike need their devices to work — maps, UPI payments, and communication all depend on a functioning phone. LocalTech keeps Tirupati's residents connected with fast doorstep repair.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "nellore",
    name: "Nellore",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Grand Trunk Road", "Magunta Layout", "Pogathota", "Santhapet", "Auto Nagar", "Vedayapalem", "Akkayyapalem", "Balaji Nagar"],
    repairMarkets: ["Grand Trunk Road Electronics", "Santhapet Market", "Magunta Layout Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 16,
    reviewCount: 128,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Nellore's prawn and aquaculture industry keeps traders and exporters on the phone all day. LocalTech ensures that when your screen cracks or battery dies, a verified technician reaches your Grand Trunk Road office or Magunta Layout home quickly.",
    nearbyCity: "chennai",
  },
  {
    slug: "karimnagar",
    name: "Karimnagar",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mankammathota", "Godavarikhani", "SR Nagar", "Vivekananda Nagar", "Jagtial Road", "AG Office Area", "Ramalayam", "Bypass Road"],
    repairMarkets: ["Mankammathota Electronics", "Main Road Market", "Jagtial Road Tech Street"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 14,
    reviewCount: 118,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Karimnagar has grown considerably since Telangana's formation, with new IT and government offices demanding reliable connectivity. LocalTech serves the city's growing middle class with verified doorstep repair from Mankammathota to the Jagtial Road corridor.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "rajahmundry",
    name: "Rajahmundry",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Innespeta", "Suryaraopet", "Godavari Bund Road", "Morampudi", "Danavaipeta", "JC Colony", "One Town", "Kakinada Road"],
    repairMarkets: ["Innespeta Electronics", "Kakinada Road Market", "One Town Tech Hub"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 13,
    reviewCount: 112,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Rajahmundry sits on the Godavari delta, a cultural hub for East Godavari district. Its professionals and students in Danavaipeta and Innespeta now get access to metro-standard repair service through LocalTech — no compromise on quality in a smaller city.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "kakinada",
    name: "Kakinada",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Suryaraopet", "Rajamahendravaram Road", "JPN Road", "Gandhi Nagar", "Bhanugudi", "Ramaraopeta", "Main Road", "Back Road"],
    repairMarkets: ["Suryaraopet Market", "Main Road Electronics", "JPN Road Tech Street"],
    priceIndex: 0.8,
    population: "4 lakh",
    techCount: 12,
    reviewCount: 106,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Kakinada's deep-water port and petrochemical companies make it an economically active city despite its size. LocalTech brings professional mobile repair to your Suryaraopet home or Gandhi Nagar office without the uncertainty of local mobile repair shops.",
    nearbyCity: "rajahmundry",
  },
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Shahganj", "Fatehabad Road", "Civil Lines", "Sikandra", "Kamla Nagar", "Dayalbagh", "Tajganj", "Mantola"],
    repairMarkets: ["Sadar Bazaar Electronics", "Shahganj Market", "Civil Lines Tech Hub"],
    priceIndex: 0.8,
    population: "18 lakh",
    techCount: 22,
    reviewCount: 153,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Agra's tourism economy means millions of visitors passing through, and a large local workforce that depends on mobile banking, UPI, and logistics apps. LocalTech covers Civil Lines and Fatehabad Road with fast doorstep repair — as quick as a Taj selfie trip.",
    nearbyCity: "delhi",
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Lanka", "Sigra", "Sunderpur", "Kotwali", "Dashashwamedh", "BHU Campus", "Nadesar", "Orderly Bazaar"],
    repairMarkets: ["Lanka Electronics", "Sigra Market", "Godowlia Market"],
    priceIndex: 0.8,
    population: "18 lakh",
    techCount: 20,
    reviewCount: 148,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "BHU's massive campus and the commercial sprawl around Lanka and Sigra make Varanasi a city of contrasts — ancient ghats, busy markets, modern students. LocalTech brings modern repair standards to all of it, from BHU hostels to the silk-weaving lanes of Orderly Bazaar.",
    nearbyCity: "patna",
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    tier: "tier2",
    areas: ["Anna Nagar", "KK Nagar", "Alagar Kovil Road", "Bypass Road", "Tallakulam", "Simmakkal", "Palanganatham", "Thirunagar"],
    repairMarkets: ["Nethaji Road Electronics", "Town Hall Market", "Bypass Road Tech Street"],
    priceIndex: 0.8,
    population: "16 lakh",
    techCount: 20,
    reviewCount: 150,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Around Meenakshi Amman Temple, Madurai's bazaars have traded for 2,500 years. LocalTech brings a different kind of trust to this city — background-checked technicians with written warranties, serving KK Nagar and the growing Bypass Road corridor.",
    nearbyCity: "coimbatore",
  },
  {
    slug: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    tier: "tier2",
    areas: ["VV Mohalla", "Kuvempunagar", "Vijayanagar", "Gokulam", "Jayalakshmipuram", "Hebbal", "Srirampura", "Nanjangud Road"],
    repairMarkets: ["Sayyaji Rao Road Electronics", "Nazarbad Market", "Vijayanagar Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 18,
    reviewCount: 139,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Mysuru's heritage status and growing IT presence in Infosys and Wipro campuses have created a population that values quality and reliability. LocalTech matches that expectation — Gokulam to Hebbal covered with technicians who document every step.",
    nearbyCity: "bangalore",
  },
  {
    slug: "mangalore",
    name: "Mangalore",
    state: "Karnataka",
    tier: "tier2",
    areas: ["Hampankatta", "Falnir", "Kankanady", "Bejai", "Attavar", "Balmatta", "Urwa", "Deralakatte"],
    repairMarkets: ["Hampankatta Electronics", "Bunder Electronics Market", "Kankanady Tech Street"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 15,
    reviewCount: 120,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Mangalore's banking and port trade culture creates a workforce that genuinely relies on phones and laptops. From Hampankatta's commercial core to the residential lanes of Kankanady, LocalTech's verified technicians keep your devices running.",
    nearbyCity: "kochi",
  },
  {
    slug: "hubli",
    name: "Hubli",
    state: "Karnataka",
    tier: "tier2",
    areas: ["Keshwapur", "Vidyanagar", "Navanagar", "Dharwad", "Unkal", "Tarihal", "Gokul Road", "Hosur"],
    repairMarkets: ["Koppikar Road Electronics", "Station Road Market", "Vidyanagar Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 17,
    reviewCount: 129,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "The Hubli-Dharwad twin city is northern Karnataka's commercial engine. LocalTech covers both sides — from Gokul Road's new apartments to Keshwapur's trading community — with same-day repair and transparent pricing.",
    nearbyCity: "bangalore",
  },
  {
    slug: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Shastri Nagar", "Ratanada", "Paota", "Sardarpura", "Pal Road", "Chopasni Housing Board", "Mandore Road", "Bhati Circle"],
    repairMarkets: ["Clock Tower Market", "Sojati Gate Electronics", "Ratanada Tech Hub"],
    priceIndex: 0.8,
    population: "16 lakh",
    techCount: 19,
    reviewCount: 141,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "The Blue City's tourism industry and defence installations both create heavy device usage. LocalTech serves Jodhpur's Shastri Nagar professionals and Ratanada families with certified doorstep repair — without the guesswork of Clock Tower's repair lane.",
    nearbyCity: "jaipur",
  },
  {
    slug: "jabalpur",
    name: "Jabalpur",
    state: "Madhya Pradesh",
    tier: "tier2",
    areas: ["Napier Town", "Vijay Nagar", "Gorakhpur", "Gwarighat Road", "Adhartal", "Civil Lines", "Ranjhi", "Damoh Naka"],
    repairMarkets: ["Napier Town Electronics", "Medical Road Market", "Sadar Bazaar Tech Hub"],
    priceIndex: 0.8,
    population: "14 lakh",
    techCount: 18,
    reviewCount: 132,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Jabalpur's military cantonments and growing commercial areas around Vijay Nagar demand reliable devices. LocalTech brings a systematic approach to repair — verified credentials, documented work, 30-day warranty — to Napier Town and Civil Lines alike.",
    nearbyCity: "bhopal",
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    tier: "tier2",
    areas: ["Lawrence Road", "Ranjit Avenue", "Green Avenue", "Hall Bazaar", "GT Road", "Chheharta", "Majitha Road", "Batala Road"],
    repairMarkets: ["Lawrence Road Electronics", "Hall Bazaar Market", "Ranjit Avenue Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 17,
    reviewCount: 128,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Near the Golden Temple and the busy Golden Circle, Amritsar's tourism and trade economy keeps people moving fast. LocalTech ensures your phone isn't the bottleneck — verified repair at your Lawrence Road hotel or Ranjit Avenue home, same day.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "ludhiana",
    name: "Ludhiana",
    state: "Punjab",
    tier: "tier2",
    areas: ["Sarabha Nagar", "Model Town", "Dugri", "Civil Lines", "BRS Nagar", "Pakhowal Road", "GT Road", "Samrala Chowk"],
    repairMarkets: ["Clock Tower Electronics", "Chaura Bazaar Market", "Model Town Tech Hub"],
    priceIndex: 0.8,
    population: "17 lakh",
    techCount: 20,
    reviewCount: 147,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Ludhiana's hosiery and cycle industry is a 24/7 operation, and so is its need for working devices. From Sarabha Nagar's executive homes to the textile mills near GT Road, LocalTech provides fast mobile repair with no disruption to your workday.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "guwahati",
    name: "Guwahati",
    state: "Assam",
    tier: "tier2",
    areas: ["Dispur", "Pan Bazaar", "Paltan Bazaar", "Chandmari", "Noonmati", "Ganeshguri", "Six Mile", "Beltola"],
    repairMarkets: ["Pan Bazaar Electronics", "Paltan Bazaar Market", "Ganeshguri Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 16,
    reviewCount: 122,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "As Northeast India's commercial gateway, Guwahati's Pan Bazaar and Dispur government corridors see high device usage. LocalTech brings professional mobile repair to a market that has historically been underserved — from Chandmari to Six Mile.",
    nearbyCity: "kolkata",
  },
  {
    slug: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    tier: "tier2",
    areas: ["Saheed Nagar", "Nayapalli", "Patia", "Khandagiri", "Bharatpur", "Jaydev Vihar", "Chandrasekharpur", "Tamando"],
    repairMarkets: ["Janpath Market Electronics", "Saheed Nagar Market", "Patia Tech Street"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 17,
    reviewCount: 127,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Bhubaneswar's IT sector in Infocity and the government offices around Nayapalli have transformed the city's device landscape. LocalTech matches that growth with certified technicians who serve Saheed Nagar and Jaydev Vihar with fast, warrantied repair.",
    nearbyCity: "kolkata",
  },
  {
    slug: "thiruvananthapuram",
    name: "Thiruvananthapuram",
    state: "Kerala",
    tier: "tier2",
    areas: ["Technopark", "Pattom", "Kowdiar", "Thampanoor", "Karamana", "Vanchiyoor", "Kesavadasapuram", "Ulloor"],
    repairMarkets: ["MG Road Electronics", "Chalai Market", "East Fort Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 18,
    reviewCount: 133,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Kerala's capital has Technopark — one of Asia's largest IT parks — producing a tech-savvy population with high device standards. LocalTech covers the Technopark campuses and Pattom's residential areas with certified repair that matches what IT professionals expect.",
    nearbyCity: "kochi",
  },
  {
    slug: "kozhikode",
    name: "Kozhikode",
    state: "Kerala",
    tier: "tier2",
    areas: ["Calicut Beach", "Medical College", "Palayam", "Mavoor Road", "Chevayur", "Arayidathupalam", "Nadakkavu", "Meenchanda"],
    repairMarkets: ["SM Street Electronics", "Palayam Market", "Big Bazaar Road Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 15,
    reviewCount: 118,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Kozhikode's IT startups and Gulf returnee economy drive strong smartphone usage — and high expectations. LocalTech brings the same trust to SM Street's repair market by putting verified, insured technicians at your Palayam doorstep.",
    nearbyCity: "kochi",
  },
  {
    slug: "nashik",
    name: "Nashik",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Gangapur Road", "College Road", "CIDCO", "Satpur", "Deolali", "Nashik Road", "Panchavati", "Trimbak Road"],
    repairMarkets: ["College Road Electronics", "Mahatma Gandhi Road Market", "CIDCO Tech Hub"],
    priceIndex: 0.8,
    population: "15 lakh",
    techCount: 19,
    reviewCount: 138,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Nashik's wine country reputation belies a serious manufacturing and tech base — defence industries at Deolali and Gangapur Road's growing residential zones both need reliable device repair. LocalTech covers all of Nashik with same-day service.",
    nearbyCity: "pune",
  },
  {
    slug: "aurangabad",
    name: "Aurangabad",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Cidco", "Garkheda", "Rauza Bagh", "Osmanpura", "Waluj", "Gulmandi", "Kranti Chowk", "Jalna Road"],
    repairMarkets: ["Gulmandi Electronics", "Kranti Chowk Market", "Jalna Road Tech Hub"],
    priceIndex: 0.8,
    population: "13 lakh",
    techCount: 17,
    reviewCount: 127,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Near the Bibi Ka Maqbara and the Ajanta-Ellora tourism belt, Aurangabad's industrial zones in Waluj and Cidco create a population that works hard and needs devices that match. LocalTech brings certified repair to your door anywhere in the city.",
    nearbyCity: "pune",
  },
  {
    slug: "solapur",
    name: "Solapur",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Vijay Nagar", "Murarji Peth", "Kamgar Nagar", "Station Road", "Hotgi Road", "Akkalkot Road", "Budhwar Peth", "Shegaon Road"],
    repairMarkets: ["Station Road Electronics", "Budhwar Peth Market", "Vijay Nagar Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 118,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Solapur's textile mills and educational institutions generate steady device usage across Vijay Nagar and the old town. LocalTech makes repair straightforward here — a verified technician to your address, a written quote, and a warranty certificate on completion.",
    nearbyCity: "pune",
  },
  {
    slug: "dehradun",
    name: "Dehradun",
    state: "Uttarakhand",
    tier: "tier2",
    areas: ["Rajpur Road", "Patel Nagar", "Vasant Vihar", "Dalanwala", "Raipur", "Clement Town", "Ballupur", "Sahastradhara Road"],
    repairMarkets: ["Paltan Bazaar Electronics", "Rajpur Road Market", "Clock Tower Tech Hub"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 15,
    reviewCount: 115,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Dehradun's school-city reputation and growing IT presence along Rajpur Road make it a city where residents expect good service. LocalTech covers the hill city's spread — from Clock Tower to Sahastradhara Road — with verified mobile repair.",
    nearbyCity: "delhi",
  },
  {
    slug: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    tier: "tier2",
    areas: ["The Mall", "Cart Road", "Lower Bazaar", "Chhota Shimla", "Vikasnagar", "Sanjauli", "Tara Devi", "Chail Road"],
    repairMarkets: ["The Mall Road Electronics", "Lower Bazaar Market", "Lakkar Bazaar Tech Hub"],
    priceIndex: 0.8,
    population: "3 lakh",
    techCount: 10,
    reviewCount: 96,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Shimla's steep hillsides mean a broken phone on the Mall Road is a real problem — there are few local options and the tourist season keeps repair shops overwhelmed. LocalTech brings a certified technician to your hotel or apartment, no trek to Lower Bazaar needed.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "ajmer",
    name: "Ajmer",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Vaishali Nagar", "Nasirabad Road", "Madar Gate", "Nala Bazaar", "Civil Lines", "Pushkar Road", "Ana Sagar", "Ramganj Mandi"],
    repairMarkets: ["Station Road Electronics", "Nala Bazaar Market", "Madar Gate Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 13,
    reviewCount: 106,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Ajmer's dargah tourism and Pushkar's fair season create a city in constant motion. LocalTech's Ajmer technicians serve Civil Lines residents and the busy Vaishali Nagar area with quick, certified repair — so pilgrims and locals alike stay connected.",
    nearbyCity: "jaipur",
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Hiran Magri", "Sector 4", "Udaipole", "Sukhadia Circle", "Fatehpura", "Bedla", "Madhuban", "Chetak Circle"],
    repairMarkets: ["Bada Bazaar Electronics", "Sukhadia Circle Market", "Chetak Circle Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 13,
    reviewCount: 108,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "The City of Lakes draws tourists and new residents in equal measure, but mobile repair options haven't kept pace. LocalTech covers Hiran Magri and Sector 4 with certified technicians — so residents of India's most scenic city don't lose sleep over a cracked screen.",
    nearbyCity: "jaipur",
  },
  {
    slug: "meerut",
    name: "Meerut",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Shastri Nagar", "Kanker Khera", "Pallavpuram", "Civil Lines", "Hapur Road", "Modipuram", "Begumpul", "Brahmpuri"],
    repairMarkets: ["Ghantaghar Market", "Civil Lines Electronics", "Hapur Road Tech Hub"],
    priceIndex: 0.8,
    population: "14 lakh",
    techCount: 18,
    reviewCount: 131,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Meerut's sports manufacturing and rising IT campuses make it a city punching above its tier. LocalTech brings professional repair to Civil Lines offices and Pallavpuram homes — with the kind of service quality that the city's newer generation demands.",
    nearbyCity: "delhi",
  },
  {
    slug: "aligarh",
    name: "Aligarh",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Ramghat Road", "Marris Road", "Medical Road", "Jamalpur", "Quarsi", "Civil Lines", "Dhanipur", "Sasni Gate"],
    repairMarkets: ["Upper Kot Market", "Civil Lines Electronics", "Medical Road Tech Hub"],
    priceIndex: 0.8,
    population: "9 lakh",
    techCount: 14,
    reviewCount: 112,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "AMU's massive campus and Aligarh's lock-manufacturing legacy both contribute to a city with strong device usage. LocalTech serves the university area and the Marris Road commercial corridor with verified repair — no Ramghat Road bargaining needed.",
    nearbyCity: "agra",
  },
  {
    slug: "bareilly",
    name: "Bareilly",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Subhash Nagar", "CB Ganj", "Pilibhit Road", "Nainital Road", "Rampur Garden", "Izzatnagar", "Badaun Road"],
    repairMarkets: ["Civil Lines Market", "Subhash Nagar Electronics", "Station Road Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 116,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Bareilly's furniture and steel industries and its role as the Rohilkhand division headquarters make it a commercially active city. LocalTech covers Civil Lines to CB Ganj with certified repair — your device gets a written estimate before work starts, every time.",
    nearbyCity: "delhi",
  },
  {
    slug: "moradabad",
    name: "Moradabad",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Brahmpuri", "Majhola", "Katghar", "Buddhi Vihar", "Pakwara", "Kanth Road", "Delhi Road"],
    repairMarkets: ["Brass Market Electronics", "Civil Lines Market", "Delhi Road Tech Hub"],
    priceIndex: 0.8,
    population: "9 lakh",
    techCount: 14,
    reviewCount: 110,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Moradabad's brass export industry keeps traders constantly in touch with buyers worldwide — a dead phone is a business problem. LocalTech covers Civil Lines and the Majhola residential areas with fast, certified repair that you don't have to negotiate for.",
    nearbyCity: "delhi",
  },
  {
    slug: "gorakhpur",
    name: "Gorakhpur",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Golghar", "Padrauna Road", "Taramandal", "Betiahata", "Basharatpur", "Medical College Road", "Bank Road"],
    repairMarkets: ["Golghar Market", "Civil Lines Electronics", "Medical College Road Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 114,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Gorakhpur, home to the Gorakhnath temple and a major railway junction, has a large mobile-using population in Civil Lines and Golghar. LocalTech brings certified repair here — technicians who come to your Betiahata home or Bank Road office.",
    nearbyCity: "varanasi",
  },
  {
    slug: "dhanbad",
    name: "Dhanbad",
    state: "Jharkhand",
    tier: "tier2",
    areas: ["Hirapur", "Jharia", "Katras", "Bank More", "Saraidhela", "Sindri", "Bhuli", "Govindpur"],
    repairMarkets: ["Bank More Electronics", "Saraidhela Market", "Hirapur Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 16,
    reviewCount: 120,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Dhanbad's coal mines and IIT(ISM) campus create a unique mix of industrial workers and top-tier students with high device dependency. LocalTech covers Bank More and Hirapur with verified repair service — consistent quality whether you're in a mine-office or a campus hostel.",
    nearbyCity: "ranchi",
  },
  // ── TELANGANA ─────────────────────────────────────────────────────────────────
  {
    slug: "nizamabad",
    name: "Nizamabad",
    state: "Telangana",
    tier: "tier2",
    areas: ["Dichpally Road", "Armoor Road", "Bus Stand Area", "Aliabad", "New Town", "District Court Area", "Vasavi Colony", "Old Town"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Station Road"],
    priceIndex: 0.75,
    population: "3.5 lakh",
    techCount: 14,
    reviewCount: 98,
    avgRating: 4.6,
    responseMinutes: "45–65",
    localIntro: "Nizamabad's turmeric and soya market traders run on mobile banking — a dead phone means a missed deal. LocalTech's verified technicians reach your Dichpally Road office or Aliabad home with doorstep repair and a 30-day warranty.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "khammam",
    name: "Khammam",
    state: "Telangana",
    tier: "tier2",
    areas: ["Wyra Road", "Yellandu Road", "Nehru Chowk", "Jalaram", "Srinivasa Nagar", "Mukhteernagar", "Gundala Road", "Old Town"],
    repairMarkets: ["Nehru Chowk Electronics", "Bus Stand Market", "Clock Tower Area"],
    priceIndex: 0.75,
    population: "2.5 lakh",
    techCount: 12,
    reviewCount: 88,
    avgRating: 4.6,
    responseMinutes: "45–65",
    localIntro: "Khammam connects the coal belt and fertile Krishna basin districts — its professionals need devices that work. LocalTech brings certified repair to your Wyra Road home or Nehru Chowk business, same day.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "mahabubnagar",
    name: "Mahabubnagar",
    state: "Telangana",
    tier: "tier2",
    areas: ["Jadcherla Road", "Bomraspet", "Surya Nagar", "Makthal Road", "Civil Lines", "Station Road", "NR Colony", "Old Town"],
    repairMarkets: ["Station Road Electronics", "Main Road Market", "Bus Stand Complex"],
    priceIndex: 0.72,
    population: "2.0 lakh",
    techCount: 10,
    reviewCount: 78,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Mahabubnagar district's farming community increasingly relies on mobile apps for market prices and UPI payments. LocalTech provides certified doorstep repair across Mahabubnagar city.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "nalgonda",
    name: "Nalgonda",
    state: "Telangana",
    tier: "tier2",
    areas: ["Miryalaguda Road", "Suryapet Road", "Srinivasa Nagar", "Vidyanagar", "Old Town", "Bus Stand Area", "Civil Lines", "Revenue Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Clock Tower Area"],
    priceIndex: 0.72,
    population: "1.5 lakh",
    techCount: 9,
    reviewCount: 72,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Nalgonda's growing town population and agricultural professionals rely on smartphones for daily trade. LocalTech fills the repair gap with verified technicians who come to you.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "adilabad",
    name: "Adilabad",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mancherial Road", "Boath Road", "DRDA Colony", "Collectorate Area", "Bus Stand", "Old Town", "Vidyanagar", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Collectorate Road"],
    priceIndex: 0.70,
    population: "1.1 lakh",
    techCount: 8,
    reviewCount: 64,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "At Telangana's northernmost tip, Adilabad's government staff and tribal welfare workers need reliable mobile service. LocalTech connects you with a verified technician for doorstep repair anywhere in the town.",
    nearbyCity: "nizamabad",
  },
  {
    slug: "ramagundam",
    name: "Ramagundam",
    state: "Telangana",
    tier: "tier2",
    areas: ["NTPC Colony", "Godavarikhani", "Pembarti", "Jyothinagar", "Srirampur", "Manthani Road", "Industrial Area", "Bus Stand"],
    repairMarkets: ["Godavarikhani Main Market", "Bus Stand Electronics", "NTPC Area Market"],
    priceIndex: 0.75,
    population: "2.4 lakh",
    techCount: 11,
    reviewCount: 84,
    avgRating: 4.5,
    responseMinutes: "45–65",
    localIntro: "Ramagundam's NTPC power plant and coal fields support thousands of technical professionals who depend on devices. LocalTech's certified technicians serve NTPC Colony and Godavarikhani with quick, priced repair.",
    nearbyCity: "karimnagar",
  },
  {
    slug: "mancherial",
    name: "Mancherial",
    state: "Telangana",
    tier: "tier2",
    areas: ["Bus Stand", "New Colony", "Luxettipet Road", "Police Quarters", "Revenue Colony", "Main Road", "Temple Street", "Gandhi Chowk"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Gandhi Chowk"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 58,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Mancherial's coal industry and agricultural hinterland create steady mobile usage. LocalTech connects Mancherial residents with verified repair technicians for doorstep service.",
    nearbyCity: "karimnagar",
  },
  {
    slug: "siddipet",
    name: "Siddipet",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Gajwel Road", "SUDA Colony", "New Town", "Bus Stand", "Old Town", "Collectorate Area", "Civil Lines"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Complex", "New Town Market"],
    priceIndex: 0.72,
    population: "1.0 lakh",
    techCount: 8,
    reviewCount: 65,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Siddipet, home to a major weaver community and growing IT offices, is expanding fast. LocalTech ensures your phone or laptop gets certified doorstep repair whether you're in the old weaving lanes or the new highway colony.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "sangareddy",
    name: "Sangareddy",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Zaheerabad Road", "Civil Lines", "Collectorate Area", "APHB Colony", "Bus Stand", "Revenue Colony", "New Town"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Hyderabad Road Complex"],
    priceIndex: 0.72,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 70,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Sangareddy is transforming with pharma and automobile industries along its national highway corridor. LocalTech provides certified mobile and laptop repair to Sangareddy's growing workforce.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "suryapet",
    name: "Suryapet",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Miryalaguda Road", "RTC Colony", "Srinivasa Nagar", "Bus Stand", "Old Town", "Revenue Colony", "Gandhi Nagar"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.70,
    population: "0.9 lakh",
    techCount: 8,
    reviewCount: 62,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Suryapet connects the Nalgonda district to Hyderabad — its traders and government staff are heavy mobile users. LocalTech brings verified repair to your home or office anywhere in Suryapet.",
    nearbyCity: "nalgonda",
  },
  {
    slug: "miryalaguda",
    name: "Miryalaguda",
    state: "Telangana",
    tier: "tier2",
    areas: ["Nalgonda Road", "Macherla Road", "Bus Stand", "Main Road", "Gandhi Nagar", "Revenue Colony", "Old Town", "Station Road"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Station Road"],
    priceIndex: 0.70,
    population: "1.0 lakh",
    techCount: 8,
    reviewCount: 60,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Miryalaguda, a key sugar production centre, has a working population that depends on mobiles for trade. LocalTech technicians cover Miryalaguda with doorstep repair backed by a 30-day warranty.",
    nearbyCity: "nalgonda",
  },
  {
    slug: "jagtial",
    name: "Jagtial",
    state: "Telangana",
    tier: "tier2",
    areas: ["Karimnagar Road", "Metpally Road", "DRDA Colony", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Municipal Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Complex", "Old Town Market"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 57,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Jagtial's paddy and turmeric economy is going digital — UPI and mobile banking are everywhere. LocalTech's verified technicians provide doorstep repair so Jagtial's farmers and traders stay connected.",
    nearbyCity: "karimnagar",
  },
  {
    slug: "kothagudem",
    name: "Kothagudem",
    state: "Telangana",
    tier: "tier2",
    areas: ["Bhadrachalam Road", "SCCL Colony", "Yellandu Road", "Bus Stand", "Main Road", "Old Town", "Revenue Colony", "Gandhi Nagar"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "SCCL Colony Market"],
    priceIndex: 0.72,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 68,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Kothagudem's coal mining heritage and forest-covered setting make it unique — but its residents need the same connected devices as any city. LocalTech delivers verified repair to your SCCL colony flat or home.",
    nearbyCity: "khammam",
  },
  {
    slug: "bhongir",
    name: "Bhongir",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Warangal Road", "Fort Area", "Main Road", "Bus Stand", "Revenue Colony", "New Colony", "Railway Station"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Highway Market"],
    priceIndex: 0.70,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 52,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bhongir's historic fort and growing highway economy host residents who need reliable device service. LocalTech covers Bhongir with verified technicians and same-day repair.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "sircilla",
    name: "Sircilla",
    state: "Telangana",
    tier: "tier2",
    areas: ["Textile Park", "Karimnagar Road", "Yellareddypet", "Bus Stand", "Main Road", "Old Town", "Power Loom Colony", "Revenue Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Textile Park Area"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 7,
    reviewCount: 54,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Sircilla's power loom industry employs thousands in its fabric corridors. LocalTech reaches textile workers and traders with mobile repair, bringing a verified technician to your home or workplace.",
    nearbyCity: "karimnagar",
  },
  {
    slug: "kamareddy",
    name: "Kamareddy",
    state: "Telangana",
    tier: "tier2",
    areas: ["Nizamabad Road", "Hyderabad Road", "Bus Stand", "Old Town", "Revenue Colony", "Civil Lines", "Gandhi Nagar", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 56,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Kamareddy's agricultural produce market and growing connectivity make mobile devices essential. LocalTech's certified technicians provide doorstep repair with warranty in Kamareddy.",
    nearbyCity: "nizamabad",
  },
  {
    slug: "nirmal",
    name: "Nirmal",
    state: "Telangana",
    tier: "tier2",
    areas: ["Adilabad Road", "Mancherial Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Industrial Area", "Nirmal Arts Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Arts Colony Area"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 54,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Nirmal, known for its lacquerware art and growing industries, has a tech-forward community. LocalTech provides certified doorstep repair for mobiles and laptops across Nirmal.",
    nearbyCity: "adilabad",
  },
  {
    slug: "nagarkurnool",
    name: "Nagarkurnool",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Achampet Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Civil Lines", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.68,
    population: "0.7 lakh",
    techCount: 6,
    reviewCount: 48,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Nagarkurnool district's Srisailam proximity and forest hinterland attract forest officers and tourism workers — all mobile-dependent. LocalTech brings repair service to this emerging town.",
    nearbyCity: "mahabubnagar",
  },
  {
    slug: "wanaparthy",
    name: "Wanaparthy",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mahabubnagar Road", "Gadwal Road", "Bus Stand", "Old Town", "Main Road", "Civil Lines", "Revenue Colony", "Palace Area"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Palace Road"],
    priceIndex: 0.68,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 46,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Wanaparthy's historic palace and growing town infrastructure are attracting new residents who depend on mobile connectivity. LocalTech serves Wanaparthy with verified doorstep repair.",
    nearbyCity: "mahabubnagar",
  },
  {
    slug: "gadwal",
    name: "Gadwal",
    state: "Telangana",
    tier: "tier2",
    areas: ["Kurnool Road", "Wanaparthy Road", "Bus Stand", "Old Town", "Main Road", "Fort Area", "Revenue Colony", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.68,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 44,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Gadwal's silk saree tradition and border-town commerce keep its residents constantly connected. LocalTech provides verified mobile repair to Gadwal's homes and businesses.",
    nearbyCity: "mahabubnagar",
  },
  {
    slug: "zaheerabad",
    name: "Zaheerabad",
    state: "Telangana",
    tier: "tier2",
    areas: ["Sangareddy Road", "Hyderabad Road", "Bus Stand", "Main Road", "Revenue Colony", "Industrial Area", "Old Town", "Railway Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Railway Station Area"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 7,
    reviewCount: 52,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Zaheerabad's industry corridor and rail connectivity make it an active commercial hub. LocalTech delivers certified mobile repair to your Zaheerabad home or workplace.",
    nearbyCity: "sangareddy",
  },
  {
    slug: "vikarabad",
    name: "Vikarabad",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Tandur Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Civil Lines", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Highway Area"],
    priceIndex: 0.70,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 48,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Vikarabad, near Hyderabad's granite belt, has a growing residential base needing mobile repair. LocalTech's technicians reach Vikarabad quickly for doorstep service.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "tandur",
    name: "Tandur",
    state: "Telangana",
    tier: "tier2",
    areas: ["Vikarabad Road", "Hyderabad Road", "Bus Stand", "Main Road", "Old Town", "Revenue Colony", "Railway Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.68,
    population: "0.5 lakh",
    techCount: 5,
    reviewCount: 40,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Tandur's limestone and cement industry workers depend on mobile devices for safety communications. LocalTech brings certified repair to Tandur's residents.",
    nearbyCity: "vikarabad",
  },
  {
    slug: "jangaon",
    name: "Jangaon",
    state: "Telangana",
    tier: "tier2",
    areas: ["Warangal Road", "Hyderabad Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Civil Lines", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Highway Market"],
    priceIndex: 0.68,
    population: "0.5 lakh",
    techCount: 5,
    reviewCount: 42,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Jangaon connects Hyderabad to Warangal with a growing population needing device services. LocalTech brings verified repair to Jangaon's homes and offices.",
    nearbyCity: "warangal",
  },
  {
    slug: "mahabubabad",
    name: "Mahabubabad",
    state: "Telangana",
    tier: "tier2",
    areas: ["Warangal Road", "Khammam Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Civil Lines", "Tribal Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Old Town Market"],
    priceIndex: 0.67,
    population: "0.5 lakh",
    techCount: 5,
    reviewCount: 38,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Mahabubabad's tribal district status and growing town area host residents deserving quality repair service. LocalTech covers Mahabubabad with certified doorstep mobile repair.",
    nearbyCity: "warangal",
  },
  {
    slug: "peddapalli",
    name: "Peddapalli",
    state: "Telangana",
    tier: "tier2",
    areas: ["Karimnagar Road", "Ramagundam Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "SCCL Area", "Railway Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Railway Area"],
    priceIndex: 0.70,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 48,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Peddapalli's power plants and coal-dependent economy keep workers connected. LocalTech provides certified mobile and laptop repair in Peddapalli.",
    nearbyCity: "karimnagar",
  },
  {
    slug: "narsampet",
    name: "Narsampet",
    state: "Telangana",
    tier: "tier2",
    areas: ["Warangal Road", "Mahabubabad Road", "Bus Stand", "Main Road", "Old Town", "Revenue Colony", "New Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Market Area"],
    priceIndex: 0.67,
    population: "0.4 lakh",
    techCount: 5,
    reviewCount: 36,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Narsampet's central Telangana location and agrarian economy are shifting to digital. LocalTech brings mobile repair to Narsampet residents at their doorstep.",
    nearbyCity: "warangal",
  },
  {
    slug: "medak",
    name: "Medak",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hyderabad Road", "Sangareddy Road", "Cathedral Area", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Cathedral Road Area"],
    priceIndex: 0.68,
    population: "0.5 lakh",
    techCount: 5,
    reviewCount: 40,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Medak's historic cathedral and district headquarters attract visitors and government workers who rely on connected devices. LocalTech provides doorstep repair in Medak.",
    nearbyCity: "sangareddy",
  },
  {
    slug: "bodhan",
    name: "Bodhan",
    state: "Telangana",
    tier: "tier2",
    areas: ["Nizamabad Road", "Sugar Factory Area", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Industrial Area", "New Colony"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Industrial Area"],
    priceIndex: 0.68,
    population: "0.7 lakh",
    techCount: 6,
    reviewCount: 46,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bodhan's sugar industry and expanding municipal area need reliable device repair. LocalTech covers Bodhan with verified technicians for doorstep mobile and appliance service.",
    nearbyCity: "nizamabad",
  },
  {
    slug: "bellampally",
    name: "Bellampally",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mancherial Road", "SCCL Colony", "Ramagundam Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Coal Area"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Colony Market"],
    priceIndex: 0.68,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 46,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bellampally's coal mining community and SCCL township residents deserve quality device repair. LocalTech provides certified doorstep service across Bellampally.",
    nearbyCity: "mancherial",
  },
  {
    slug: "palvancha",
    name: "Palvancha",
    state: "Telangana",
    tier: "tier2",
    areas: ["Kothagudem Road", "Bhadrachalam Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "New Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Market Area"],
    priceIndex: 0.68,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 44,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Palvancha near Bhadrachalam connects pilgrims and coal workers — both need functioning mobile devices. LocalTech's verified technicians serve Palvancha with doorstep repair.",
    nearbyCity: "kothagudem",
  },
  {
    slug: "narayanpet",
    name: "Narayanpet",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mahabubnagar Road", "Kurnool Road", "Bus Stand", "Old Town", "Main Road", "Revenue Colony", "Handloom Colony", "Civil Lines"],
    repairMarkets: ["Main Road Electronics", "Bus Stand Market", "Handloom Colony Area"],
    priceIndex: 0.67,
    population: "0.4 lakh",
    techCount: 5,
    reviewCount: 36,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Narayanpet's handloom saree industry is going digital with mobile-based orders. LocalTech brings certified mobile repair to weavers and traders in Narayanpet.",
    nearbyCity: "mahabubnagar",
  },
  // ── ANDHRA PRADESH ────────────────────────────────────────────────────────────
  {
    slug: "kurnool",
    name: "Kurnool",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Budhawarpet", "Sanjay Gandhi Colony", "Bellary Road", "Hyderabad Road", "Gandhinagar", "CTO Area", "Pavadapuram", "Lalcheruvu"],
    repairMarkets: ["Budhawarpet Electronics", "Bellary Road Market", "Old Town Market"],
    priceIndex: 0.78,
    population: "4.8 lakh",
    techCount: 16,
    reviewCount: 108,
    avgRating: 4.6,
    responseMinutes: "45–65",
    localIntro: "Kurnool — Andhra's cement capital — has a large commercial and professional class that can't afford mobile downtime. LocalTech's certified technicians cover Budhawarpet and Sanjay Gandhi Colony with doorstep repair.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "anantapur",
    name: "Anantapur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Subash Road", "New Town", "Old Town", "Raptadu Road", "Gooty Road", "Bhaskara Nagar", "JC Nagar", "Bus Stand"],
    repairMarkets: ["Subash Road Electronics", "Old Town Market", "New Town Complex"],
    priceIndex: 0.75,
    population: "2.8 lakh",
    techCount: 13,
    reviewCount: 92,
    avgRating: 4.5,
    responseMinutes: "45–65",
    localIntro: "Anantapur's granite and groundnut belt trade runs on mobile connectivity. LocalTech brings certified repair to Subash Road offices and New Town homes, same day.",
    nearbyCity: "bangalore",
  },
  {
    slug: "kadapa",
    name: "Kadapa",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Gandhi Road", "Cuddapah Town", "Nethaji Road", "Srinivasa Nagar", "RTC Complex", "Bypass Road", "Rajampet Road", "Old Town"],
    repairMarkets: ["Gandhi Road Electronics", "RTC Complex Market", "Bypass Road Market"],
    priceIndex: 0.75,
    population: "3.4 lakh",
    techCount: 14,
    reviewCount: 96,
    avgRating: 4.6,
    responseMinutes: "45–65",
    localIntro: "Kadapa's cement and mining industries and growing education sector make mobile devices essential tools. LocalTech delivers doorstep repair across all major areas of Kadapa.",
    nearbyCity: "tirupati",
  },
  {
    slug: "ongole",
    name: "Ongole",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Kurnool Road", "Narasaraopet Road", "RTC Complex", "Gandhi Nagar", "Old Town", "Mangalagiri Road", "Bypass Road", "New Town"],
    repairMarkets: ["Main Road Electronics", "RTC Complex Market", "Old Town Market"],
    priceIndex: 0.75,
    population: "2.2 lakh",
    techCount: 11,
    reviewCount: 82,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Ongole's Prakasam district headquarters and strong agriculture economy create a mobile-dependent business community. LocalTech covers Ongole with verified doorstep repair.",
    nearbyCity: "guntur",
  },
  {
    slug: "chittoor",
    name: "Chittoor",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Tirupati Road", "Vellore Road", "RTC Complex", "Gandhi Nagar", "Old Town", "New Colony", "Bypass Road", "Market Area"],
    repairMarkets: ["Main Road Electronics", "RTC Market", "Bypass Road Complex"],
    priceIndex: 0.75,
    population: "1.6 lakh",
    techCount: 10,
    reviewCount: 78,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Chittoor's mango and milk cooperative economy is going digital fast. LocalTech brings certified mobile and laptop repair to Chittoor's homes and offices, doorstep.",
    nearbyCity: "tirupati",
  },
  {
    slug: "madanapalle",
    name: "Madanapalle",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Horsley Hills Road", "Chittoor Road", "Old Town", "RTC Complex", "Market Area", "College Road", "New Colony", "Bus Stand"],
    repairMarkets: ["Main Road Electronics", "RTC Market", "Market Area"],
    priceIndex: 0.72,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 70,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Madanapalle, the birthplace of Pingali Venkayya, has a large student population needing reliable mobile repair. LocalTech serves students and professionals alike with doorstep service.",
    nearbyCity: "chittoor",
  },
  {
    slug: "kavali",
    name: "Kavali",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Nellore Road", "Ongole Road", "RTC Complex", "Old Town", "Main Road", "Railway Station", "New Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "RTC Market", "Market Area"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 7,
    reviewCount: 54,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Kavali's coastal economy and growing trade community rely on mobile connectivity. LocalTech brings verified repair to Kavali homes and businesses.",
    nearbyCity: "nellore",
  },
  {
    slug: "gudur",
    name: "Gudur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Chennai Road", "Nellore Road", "Railway Colony", "Old Town", "Main Road", "Bus Stand", "New Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "Railway Market", "Market Area"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 7,
    reviewCount: 52,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Gudur's railway junction makes it a busy trading point. LocalTech provides verified mobile repair for Gudur's commercial and residential communities.",
    nearbyCity: "nellore",
  },
  {
    slug: "eluru",
    name: "Eluru",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Vijayawada Road", "Rajahmundry Road", "RTC Complex", "Old Town", "Gandhi Nagar", "Bypass Road", "New Colony", "Market Area"],
    repairMarkets: ["Main Road Electronics", "Old Town Market", "Bypass Road Complex"],
    priceIndex: 0.78,
    population: "2.0 lakh",
    techCount: 12,
    reviewCount: 86,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Eluru, the West Godavari headquarters, has a strong trade community and growing residential zones. LocalTech brings certified mobile and laptop repair to your Eluru home or office.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "bhimavaram",
    name: "Bhimavaram",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Eluru Road", "Undi Road", "RTC Complex", "Old Town", "Market Area", "New Colony", "Krishna Lanka", "Bypass Road"],
    repairMarkets: ["Main Road Electronics", "Old Town Market", "Bypass Road"],
    priceIndex: 0.75,
    population: "1.5 lakh",
    techCount: 10,
    reviewCount: 78,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Bhimavaram, famed for its sweets and fish trade, has a commercially active population that runs on smartphones. LocalTech's verified technicians provide doorstep repair across Bhimavaram.",
    nearbyCity: "eluru",
  },
  {
    slug: "tanuku",
    name: "Tanuku",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Bhimavaram Road", "Nidadavolu Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Railway Station", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 56,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Tanuku's coconut and rice mills and coastal connectivity keep its traders on mobile devices. LocalTech provides certified doorstep repair in Tanuku.",
    nearbyCity: "bhimavaram",
  },
  {
    slug: "tadepalligudem",
    name: "Tadepalligudem",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Eluru Road", "Bhimavaram Road", "RTC Complex", "Old Town", "Market Area", "New Colony", "Bus Stand", "Railway Colony"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Railway Station Area"],
    priceIndex: 0.72,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 68,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Tadepalligudem's role as a West Godavari trading hub means its professionals need always-on mobile connectivity. LocalTech provides doorstep repair with a 30-day warranty.",
    nearbyCity: "eluru",
  },
  {
    slug: "machilipatnam",
    name: "Machilipatnam",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Vijayawada Road", "Port Area", "Old Town", "Market Area", "RTC Complex", "New Colony", "Bus Stand", "Beach Road"],
    repairMarkets: ["Main Road Electronics", "Old Town Market", "RTC Complex"],
    priceIndex: 0.72,
    population: "1.6 lakh",
    techCount: 10,
    reviewCount: 76,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Machilipatnam, one of India's oldest port cities, has a trading class that relies on smartphones and laptops. LocalTech brings certified repair to your Old Town home or Port Area office.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "gudivada",
    name: "Gudivada",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Vijayawada Road", "Machilipatnam Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "RTC Complex", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Old Town Market"],
    priceIndex: 0.70,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 68,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Gudivada's proximity to Vijayawada and strong agriculture trade make mobile devices daily essentials. LocalTech provides doorstep repair across Gudivada.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "tenali",
    name: "Tenali",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Guntur Road", "Vijayawada Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "RTC Complex", "Pallavi Nagar"],
    repairMarkets: ["Main Road Electronics", "Market Area", "RTC Complex"],
    priceIndex: 0.72,
    population: "1.7 lakh",
    techCount: 11,
    reviewCount: 80,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Tenali's trade and agriculture community is very serious about mobile connectivity. LocalTech serves Tenali with certified doorstep repair.",
    nearbyCity: "guntur",
  },
  {
    slug: "narasaraopet",
    name: "Narasaraopet",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Guntur Road", "Hyderabad Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "College Road", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 7,
    reviewCount: 54,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Narasaraopet's Palnadu connection and growing student population need reliable mobile repair. LocalTech brings verified technicians for doorstep service in Narasaraopet.",
    nearbyCity: "guntur",
  },
  {
    slug: "bapatla",
    name: "Bapatla",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Chirala Road", "Guntur Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Beach Road", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Area"],
    priceIndex: 0.70,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 48,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bapatla, a new district headquarters with coastal access, is growing fast. LocalTech provides certified doorstep mobile repair to Bapatla's expanding community.",
    nearbyCity: "guntur",
  },
  {
    slug: "chirala",
    name: "Chirala",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Ongole Road", "Bapatla Road", "Old Town", "Market Area", "Textile Park", "Bus Stand", "Railway Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Old Town Market", "Textile Area"],
    priceIndex: 0.72,
    population: "1.5 lakh",
    techCount: 10,
    reviewCount: 74,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Chirala's textile industry and APSEZ port zone create a mobile-dependent workforce. LocalTech delivers certified repair to your Chirala home or workplace.",
    nearbyCity: "ongole",
  },
  {
    slug: "nandyal",
    name: "Nandyal",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Kurnool Road", "Atmakur Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Railway Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Old Town Market", "Railway Area"],
    priceIndex: 0.72,
    population: "2.3 lakh",
    techCount: 11,
    reviewCount: 82,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Nandyal, the new district headquarters in the Kurnool region, is quickly urbanizing. LocalTech provides doorstep mobile and appliance repair to Nandyal's growing population.",
    nearbyCity: "kurnool",
  },
  {
    slug: "adoni",
    name: "Adoni",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Kurnool Road", "Bellary Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Cotton Market", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Cotton Market Area", "Bus Stand Complex"],
    priceIndex: 0.72,
    population: "1.7 lakh",
    techCount: 10,
    reviewCount: 74,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Adoni's cotton textile industry and busy market are fuelled by mobile commerce. LocalTech delivers certified doorstep repair to Adoni's traders and residents.",
    nearbyCity: "kurnool",
  },
  {
    slug: "guntakal",
    name: "Guntakal",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Railway Junction Area", "Anantapur Road", "Bellary Road", "Old Town", "New Colony", "Bus Stand", "Market Area", "Main Road"],
    repairMarkets: ["Railway Area Electronics", "Main Road Market", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "1.2 lakh",
    techCount: 9,
    reviewCount: 70,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Guntakal's major railway junction creates a busy commercial town with railway workers and traders needing reliable mobile devices. LocalTech serves Guntakal with doorstep repair.",
    nearbyCity: "anantapur",
  },
  {
    slug: "dharmavaram",
    name: "Dharmavaram",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Anantapur Road", "Gooty Road", "Old Town", "Market Area", "Silk Weaving Colony", "Bus Stand", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Silk Market Area", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "1.0 lakh",
    techCount: 8,
    reviewCount: 64,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Dharmavaram's silk saree tradition is backed by a modern business community. LocalTech provides certified mobile repair so Dharmavaram's weavers and traders stay connected.",
    nearbyCity: "anantapur",
  },
  {
    slug: "hindupur",
    name: "Hindupur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Bangalore Road", "Anantapur Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Industrial Area", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Industrial Complex"],
    priceIndex: 0.72,
    population: "0.8 lakh",
    techCount: 8,
    reviewCount: 62,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Hindupur, close to Bangalore and with a growing industrial base, has tech-savvy residents expecting quality repair. LocalTech provides certified doorstep service across Hindupur.",
    nearbyCity: "bangalore",
  },
  {
    slug: "proddatur",
    name: "Proddatur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Kadapa Road", "Jammalamadugu Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Cotton Market", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Cotton Market"],
    priceIndex: 0.72,
    population: "1.9 lakh",
    techCount: 11,
    reviewCount: 80,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Proddatur's textile and cotton trade is growing, and so is its mobile usage. LocalTech delivers certified doorstep repair to Proddatur's businesses and homes.",
    nearbyCity: "kadapa",
  },
  {
    slug: "vizianagaram",
    name: "Vizianagaram",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Visakhapatnam Road", "Srikakulam Road", "Fort Area", "Old Town", "Market Area", "New Colony", "Bus Stand", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Fort Area Market", "Bus Stand Complex"],
    priceIndex: 0.75,
    population: "2.3 lakh",
    techCount: 12,
    reviewCount: 86,
    avgRating: 4.5,
    responseMinutes: "45–65",
    localIntro: "Vizianagaram, the Vizag Metro's neighbouring city, is growing with colleges and government offices. LocalTech brings certified mobile repair to your Fort Area or New Colony home.",
    nearbyCity: "visakhapatnam",
  },
  {
    slug: "srikakulam",
    name: "Srikakulam",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Vizianagaram Road", "Narasannapeta Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Railway Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Complex"],
    priceIndex: 0.72,
    population: "1.2 lakh",
    techCount: 9,
    reviewCount: 70,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Srikakulam's coastal district and new industrial growth need reliable mobile service. LocalTech provides certified doorstep repair to Srikakulam's residents and businesses.",
    nearbyCity: "vizianagaram",
  },
  {
    slug: "bobbili",
    name: "Bobbili",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Vizianagaram Road", "Rajam Road", "Old Town", "Market Area", "Fort Area", "Bus Stand", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Fort Area Market"],
    priceIndex: 0.68,
    population: "0.6 lakh",
    techCount: 6,
    reviewCount: 46,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bobbili's historic veena-crafting tradition and growing commerce attract a mobile-dependent population. LocalTech provides verified repair in Bobbili.",
    nearbyCity: "vizianagaram",
  },
  {
    slug: "amalapuram",
    name: "Amalapuram",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Rajahmundry Road", "Razole Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Coconut Market", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "0.9 lakh",
    techCount: 8,
    reviewCount: 60,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Amalapuram's East Godavari delta position and aquaculture trade make it a commercially active town. LocalTech brings mobile repair to Amalapuram's doorstep.",
    nearbyCity: "rajahmundry",
  },
  {
    slug: "anakapalle",
    name: "Anakapalle",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Visakhapatnam Road", "Yelamanchili Road", "Old Town", "Market Area", "Industrial Area", "Bus Stand", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Industrial Area Market"],
    priceIndex: 0.72,
    population: "1.1 lakh",
    techCount: 9,
    reviewCount: 68,
    avgRating: 4.5,
    responseMinutes: "50–70",
    localIntro: "Anakapalle, a new Andhra Pradesh district headquarters near Vizag, is urbanizing rapidly. LocalTech serves this growing city with certified doorstep mobile and laptop repair.",
    nearbyCity: "visakhapatnam",
  },
  {
    slug: "narasapuram",
    name: "Narasapuram",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Bhimavaram Road", "Eluru Road", "Old Town", "Market Area", "Coconut Port Area", "Bus Stand", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Port Area Market"],
    priceIndex: 0.70,
    population: "0.9 lakh",
    techCount: 7,
    reviewCount: 56,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Narasapuram's coconut trade and river commerce keep its residents connected. LocalTech provides certified mobile repair to Narasapuram's homes and businesses.",
    nearbyCity: "bhimavaram",
  },
  {
    slug: "tadpatri",
    name: "Tadpatri",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Anantapur Road", "Kurnool Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Cement Area", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Bus Stand Complex"],
    priceIndex: 0.70,
    population: "0.8 lakh",
    techCount: 7,
    reviewCount: 54,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Tadpatri's cement industry and agricultural base are going digital with mobile banking. LocalTech provides doorstep repair to Tadpatri's working community.",
    nearbyCity: "anantapur",
  },
  {
    slug: "palasa",
    name: "Palasa",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Srikakulam Road", "Odisha Border Area", "Old Town", "Market Area", "Bus Stand", "Railway Colony", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Railway Station Area"],
    priceIndex: 0.68,
    population: "0.5 lakh",
    techCount: 5,
    reviewCount: 40,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Palasa's border location with Odisha creates cross-border trade that runs on mobile connectivity. LocalTech provides certified repair to Palasa's residents.",
    nearbyCity: "srikakulam",
  },
  {
    slug: "samalkot",
    name: "Samalkot",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Kakinada Road", "Rajahmundry Road", "Old Town", "College Area", "Market Area", "Bus Stand", "New Colony", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "College Area"],
    priceIndex: 0.70,
    population: "0.7 lakh",
    techCount: 6,
    reviewCount: 50,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Samalkot's educational institutions and Godavari delta location create a mobile-heavy population. LocalTech provides doorstep repair to Samalkot's students and residents.",
    nearbyCity: "kakinada",
  },
  {
    slug: "bheemunipatnam",
    name: "Bheemunipatnam",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Visakhapatnam Road", "Beach Road", "Old Town", "Market Area", "New Colony", "Bus Stand", "Port Area", "Main Road"],
    repairMarkets: ["Main Road Electronics", "Market Area", "Beach Road"],
    priceIndex: 0.70,
    population: "0.4 lakh",
    techCount: 5,
    reviewCount: 38,
    avgRating: 4.5,
    responseMinutes: "55–75",
    localIntro: "Bheemunipatnam's beach economy and proximity to Vizag create a holiday and residential mix. LocalTech provides mobile repair close to Vizag at Bheemunipatnam's doorstep.",
    nearbyCity: "visakhapatnam",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getCitiesByState(state: string): CityData[] {
  return CITIES.filter((c) => c.state === state);
}
