export type CityTier = "metro" | "tier1" | "tier2";

export interface CityData {
  slug: string;
  name: string;
  state: string;
  tier: CityTier;
  areas: string[];
  repairMarkets: string[];
  priceIndex: number;
  population: string;
  techCount: number;
  reviewCount: number;
  avgRating: number;
  responseMinutes: string;
  localIntro: string;
  nearbyCity?: string;
}

export const CITIES: CityData[] = [
  // METRO
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    tier: "metro",
    areas: ["HITEC City", "Banjara Hills", "Jubilee Hills", "Kondapur", "Gachibowli", "Madhapur", "Ameerpet", "Kukatpally"],
    repairMarkets: ["Abids Electronics Market", "Secunderabad Clock Tower Market", "SR Nagar Computer Market"],
    priceIndex: 1.0,
    population: "1.0 crore",
    techCount: 140,
    reviewCount: 312,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "From the tech corridors of HITEC City to the bustling lanes near Charminar, LocalTech certified technicians reach you across Hyderabad — typically within 40 minutes. Whether you work in Gachibowli's glass towers or live in the old-city bylanes, we come to you.",
  },
  {
    slug: "bangalore",
    name: "Bangalore",
    state: "Karnataka",
    tier: "metro",
    areas: ["Koramangala", "Indiranagar", "Whitefield", "HSR Layout", "Jayanagar", "Electronic City", "Marathahalli", "BTM Layout"],
    repairMarkets: ["SP Road Electronics", "Chickpet Electronics", "Nehru Street Shivajinagar"],
    priceIndex: 1.0,
    population: "1.4 crore",
    techCount: 155,
    reviewCount: 387,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Bangalore runs on screens — from laptop-laden cafes in Koramangala to the startup offices packed along ORR. When your device breaks mid-sprint, LocalTech dispatches a verified technician to your desk or doorstep, often before your next standup.",
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    tier: "metro",
    areas: ["Andheri", "Bandra", "Thane", "Navi Mumbai", "Borivali", "Dadar", "Kurla", "Malad"],
    repairMarkets: ["Lamington Road Electronics", "Heera Panna Market", "Ghatkopar Electronics Market"],
    priceIndex: 1.0,
    population: "2.0 crore",
    techCount: 170,
    reviewCount: 401,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "In a city that never stops — from Andheri's offices to Thane's apartments — a broken phone costs you more than money. LocalTech same-day repair serves all of Mumbai with no traffic excuses; our technicians know every shortcut.",
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    tier: "metro",
    areas: ["Connaught Place", "Lajpat Nagar", "Dwarka", "Rohini", "Janakpuri", "Saket", "Noida Extension", "Greater Noida"],
    repairMarkets: ["Nehru Place Electronics", "Lajpat Nagar Market", "Palika Bazaar"],
    priceIndex: 1.0,
    population: "1.9 crore",
    techCount: 160,
    reviewCount: 375,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Delhi's repair ecosystem stretches from Nehru Place's wholesale shops to the GK boutiques — but price transparency is rare. LocalTech brings fixed, upfront pricing and background-verified technicians to your door, from Dwarka to Noida in a single platform.",
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    tier: "metro",
    areas: ["Anna Nagar", "T. Nagar", "Velachery", "Porur", "Adyar", "Chromepet", "Tambaram", "OMR"],
    repairMarkets: ["Ritchie Street Electronics", "Anna Salai Market", "Parrys Corner"],
    priceIndex: 1.0,
    population: "1.1 crore",
    techCount: 130,
    reviewCount: 295,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "From the IT corridors along OMR to the dense residential blocks of Anna Nagar, Chennai has one of India's highest smartphone ownership rates per household. LocalTech connects you with certified technicians who know the city's traffic patterns and reach you fast.",
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    tier: "metro",
    areas: ["Salt Lake", "New Town", "Park Street", "Howrah", "Dumdum", "Behala", "Tollygunge", "Jadavpur"],
    repairMarkets: ["Chandni Chowk Electronics", "Esplanade Market", "Hatibagan Market"],
    priceIndex: 1.0,
    population: "1.5 crore",
    techCount: 120,
    reviewCount: 267,
    avgRating: 4.7,
    responseMinutes: "35–45",
    localIntro: "Kolkata's New Town tech hubs and the old-school electronics lanes of Chandni Chowk sit 40 minutes apart, but repair quality varies wildly. LocalTech's vetted technicians bring consistent, priced service whether you're in Salt Lake Sector V or Howrah.",
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    tier: "metro",
    areas: ["Kothrud", "Hinjewadi", "Viman Nagar", "Hadapsar", "Kalyani Nagar", "FC Road", "Baner", "Wakad"],
    repairMarkets: ["Budhwar Peth Electronics", "Camp Market", "FC Road IT Hub"],
    priceIndex: 1.0,
    population: "73 lakh",
    techCount: 115,
    reviewCount: 248,
    avgRating: 4.8,
    responseMinutes: "35–45",
    localIntro: "Pune's student neighbourhoods near FC Road and the IT parks of Hinjewadi both demand fast, reliable device repair. LocalTech covers all of Pune's rapidly growing boundaries — from Wakad to Hadapsar — with technicians who've passed a practical skills test.",
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    tier: "metro",
    areas: ["CG Road", "Navrangpura", "SG Highway", "Satellite", "Bopal", "Prahlad Nagar", "Vastrapur", "Maninagar"],
    repairMarkets: ["Manek Chowk Electronics", "Relief Road Market", "CG Road Tech Market"],
    priceIndex: 1.0,
    population: "82 lakh",
    techCount: 110,
    reviewCount: 231,
    avgRating: 4.7,
    responseMinutes: "35–45",
    localIntro: "Ahmedabad's CG Road corridor and the spreading tech districts around SG Highway have a rapidly growing device-dependent workforce. LocalTech brings certified repair service to your home or office — from the old city near Manek Chowk to the new campuses in GIFT City.",
  },
  // TIER 1
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    tier: "tier1",
    areas: ["Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Mansarovar", "Jagatpura", "Tonk Road", "Bani Park", "Raja Park"],
    repairMarkets: ["Nehru Bazaar Electronics", "Ashok Nagar Market", "MI Road Tech Market"],
    priceIndex: 0.9,
    population: "40 lakh",
    techCount: 52,
    reviewCount: 187,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Behind Jaipur's Pink City walls, a new generation of device users in Malviya Nagar and Vaishali Nagar need repair services that match their pace. LocalTech brings fixed-price transparency to a market often dominated by Nehru Bazaar's bargain shops.",
    nearbyCity: "delhi",
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    tier: "tier1",
    areas: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar", "Alambagh", "Vikas Nagar", "Charbagh", "Rajajipuram"],
    repairMarkets: ["Sadar Electronics Market", "Aminabad Market", "Hazratganj Tech Hub"],
    priceIndex: 0.9,
    population: "36 lakh",
    techCount: 48,
    reviewCount: 175,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Lucknow's Gomti Nagar IT corridor and the old-city lanes near Aminabad both have device users looking for honest repair. LocalTech's technicians navigate the city's famous traffic to reach you — bringing a written estimate before touching your phone.",
    nearbyCity: "delhi",
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    tier: "tier1",
    areas: ["Kakkanad", "Edapally", "MG Road", "Aluva", "Thrikkakara", "Marine Drive", "Panampilly Nagar", "Vyttila"],
    repairMarkets: ["Broadway Market", "MG Road Electronics", "Edapally Electronics Hub"],
    priceIndex: 0.9,
    population: "22 lakh",
    techCount: 45,
    reviewCount: 168,
    avgRating: 4.8,
    responseMinutes: "40–55",
    localIntro: "Kochi's Kakkanad technopark hosts thousands of IT professionals who can't afford device downtime. LocalTech ensures a vetted technician reaches you on Infopark campus or your Marine Drive apartment, usually within the hour.",
    nearbyCity: "thiruvananthapuram",
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Punjab/Haryana",
    tier: "tier1",
    areas: ["Sector 17", "Sector 22", "Sector 35", "Panchkula", "Mohali", "Zirakpur", "Manimajra", "Sector 43"],
    repairMarkets: ["Sector 22 Electronics", "Sector 17 Market", "Mohali Phase 7 Market"],
    priceIndex: 0.9,
    population: "12 lakh",
    techCount: 38,
    reviewCount: 152,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Chandigarh's planned grid makes doorstep service genuinely fast — our technicians use sector addresses to find you in minutes, not hours. From Sector 17's commercial heart to Mohali's IT Park, LocalTech covers the entire tricity.",
    nearbyCity: "amritsar",
  },
  {
    slug: "coimbatore",
    name: "Coimbatore",
    state: "Tamil Nadu",
    tier: "tier1",
    areas: ["RS Puram", "Gandhipuram", "Peelamedu", "Saibaba Colony", "Singanallur", "Kovai Pudur", "Race Course", "Vadavalli"],
    repairMarkets: ["Big Bazaar Street Electronics", "Oppanakara Street Market", "DB Road Tech Market"],
    priceIndex: 0.9,
    population: "21 lakh",
    techCount: 42,
    reviewCount: 161,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Coimbatore's textile and engineering industries run on mobile connectivity, making fast repair essential. LocalTech serves RS Puram's offices and Peelamedu's student hubs equally — with transparent pricing that beats the walk-in shops on Oppanakara Street.",
    nearbyCity: "chennai",
  },
  {
    slug: "bhopal",
    name: "Bhopal",
    state: "Madhya Pradesh",
    tier: "tier1",
    areas: ["MP Nagar", "Arera Colony", "New Market", "Hoshangabad Road", "Kolar", "Lalghati", "Karond", "BHEL"],
    repairMarkets: ["New Market Electronics", "DB Mall Tech Hub", "MP Nagar Computer Market"],
    priceIndex: 0.9,
    population: "24 lakh",
    techCount: 40,
    reviewCount: 158,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Bhopal's dual urban core — old city around New Market and the new zones along Hoshangabad Road — spans a wide geography. LocalTech's technicians are stationed across both sides so your wait time stays short wherever you are.",
    nearbyCity: "indore",
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    tier: "tier1",
    areas: ["Vijay Nagar", "Palasia", "MG Road", "Rau", "Nipania", "Scheme 54", "LIG Colony", "Lasudia"],
    repairMarkets: ["Electronics Complex Palasia", "MG Road Market", "Malhar Mega Mall Tech Street"],
    priceIndex: 0.9,
    population: "35 lakh",
    techCount: 50,
    reviewCount: 179,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Indore ranked India's cleanest city for six straight years — and its smartphone repair market matches that appetite for quality. LocalTech brings the same standard to your device: verified technicians, clean workmanship, upfront pricing, no mess left behind.",
    nearbyCity: "bhopal",
  },
  {
    slug: "nagpur",
    name: "Nagpur",
    state: "Maharashtra",
    tier: "tier1",
    areas: ["Dharampeth", "Sitabuldi", "Laxmi Nagar", "Nagpur University Road", "Wardha Road", "Amravati Road", "Hingna", "Wadi"],
    repairMarkets: ["Sitabuldi Market", "Dharampeth Electronics", "Lokmat Square Tech Market"],
    priceIndex: 0.9,
    population: "27 lakh",
    techCount: 44,
    reviewCount: 163,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "At the geographic centre of India, Nagpur's MIHAN aerospace and IT zone is growing fast — and its device users expect metro-class repair. LocalTech delivers that with verified technicians across Dharampeth, Laxmi Nagar, and the new Wardha Road development.",
    nearbyCity: "pune",
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    tier: "tier1",
    areas: ["Dwaraka Nagar", "MVP Colony", "Rushikonda", "Gajuwaka", "Seethammadhara", "Waltair", "NAD Junction", "Steel Plant"],
    repairMarkets: ["Dwaraka Nagar Electronics", "RTC Complex Market", "MVP Colony Tech Street"],
    priceIndex: 0.9,
    population: "21 lakh",
    techCount: 43,
    reviewCount: 160,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Vizag's navy base, port, and steel plant create a working population that depends on devices around the clock. LocalTech covers the whole city — from the beachfront apartments at Rushikonda to the industrial township near Gajuwaka — with same-day repair.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "surat",
    name: "Surat",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Adajan", "Vesu", "Katargam", "Udhna", "Ring Road", "Althan", "Piplod", "Bhatar Road"],
    repairMarkets: ["Ghod Dod Road Electronics", "Varachha Market", "Katargam Tech Hub"],
    priceIndex: 0.9,
    population: "73 lakh",
    techCount: 55,
    reviewCount: 196,
    avgRating: 4.7,
    responseMinutes: "40–55",
    localIntro: "Surat's diamond and textile traders move fast — they need devices that work. From the busy lanes of Katargam to the new residential towers in Vesu, LocalTech gets a verified technician to your door before your next business call.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "vadodara",
    name: "Vadodara",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Alkapuri", "Manjalpur", "Gorwa", "Fatehgunj", "Race Course", "Gotri", "Karelibaug", "Waghodia Road"],
    repairMarkets: ["Sursagar Electronics", "Sayajigunj Market", "Alkapuri Tech Street"],
    priceIndex: 0.9,
    population: "22 lakh",
    techCount: 40,
    reviewCount: 153,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Vadodara's Alkapuri and the Sayaji Baug neighbourhood have a high density of professionals who need reliable repair without the guesswork of local shops. LocalTech gives you a certified tech with a quoted price, not a verbal estimate that doubles at collection.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "rajkot",
    name: "Rajkot",
    state: "Gujarat",
    tier: "tier1",
    areas: ["Kalawad Road", "University Road", "Jagnath Plot", "Mavdi", "Raiya Road", "150 Feet Ring Road", "Yagnik Road", "Nana Mava"],
    repairMarkets: ["Dhebar Road Electronics", "Gondal Road Market", "Kalavad Road Tech Hub"],
    priceIndex: 0.9,
    population: "19 lakh",
    techCount: 36,
    reviewCount: 144,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Rajkot's SME ecosystem — from auto-parts manufacturers to engineering firms along the 150 Feet Ring Road — relies heavily on mobile connectivity. LocalTech brings dependable, priced repair service across Rajkot without the need to find parking near Dhebar Road shops.",
    nearbyCity: "ahmedabad",
  },
  {
    slug: "patna",
    name: "Patna",
    state: "Bihar",
    tier: "tier1",
    areas: ["Boring Road", "Fraser Road", "Bailey Road", "Kankarbagh", "Rajendra Nagar", "Patliputra Colony", "Danapur", "Phulwari"],
    repairMarkets: ["Boring Road Electronics", "Dakbungalow Market", "Fraser Road Tech Market"],
    priceIndex: 0.9,
    population: "25 lakh",
    techCount: 38,
    reviewCount: 148,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Patna's Boring Road has become the city's go-to strip for anything tech, but the repair options are a mixed bag. LocalTech filters that out — you get a screened technician with parts warranty, whether you're in Kankarbagh or Patliputra Colony.",
    nearbyCity: "varanasi",
  },
  {
    slug: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    tier: "tier1",
    areas: ["Harmu Road", "Lalpur", "Doranda", "Bariatu", "Namkum", "Kanke Road", "Argora", "Hinoo"],
    repairMarkets: ["Station Road Electronics", "Main Road Market", "Firayalal Chowk Tech Hub"],
    priceIndex: 0.9,
    population: "14 lakh",
    techCount: 32,
    reviewCount: 136,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "Ranchi has grown quickly as a government and commercial hub, but quality device repair has lagged behind. LocalTech is changing that — bringing verified technicians to Lalpur, Harmu Road, and Bariatu with service standards that match what Ranchi's workforce expects.",
    nearbyCity: "patna",
  },
  {
    slug: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    tier: "tier1",
    areas: ["Shankar Nagar", "Pandri", "Devendra Nagar", "Telibandha", "Tikrapara", "GE Road", "Fafadih", "Amanaka"],
    repairMarkets: ["Malviya Road Electronics", "Pandri Market", "Shankar Nagar Tech Street"],
    priceIndex: 0.9,
    population: "13 lakh",
    techCount: 30,
    reviewCount: 130,
    avgRating: 4.6,
    responseMinutes: "40–55",
    localIntro: "As Chhattisgarh's capital, Raipur is growing fast — new apartments in Devendra Nagar and the commercial bustle on GE Road both need reliable repair service. LocalTech connects you to vetted technicians who come to you, no auto-rickshaw trip to Malviya Road required.",
    nearbyCity: "nagpur",
  },
  // TIER 2
  {
    slug: "vijayawada",
    name: "Vijayawada",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Patamata", "Benz Circle", "Governorpet", "Labbipet", "Suryaraopet", "Moghalrajpuram", "MG Road", "Auto Nagar"],
    repairMarkets: ["Eluru Road Electronics", "Benz Circle Market", "Krishna Lanka Tech Street"],
    priceIndex: 0.8,
    population: "11 lakh",
    techCount: 22,
    reviewCount: 164,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Whether you're near the Prakasam Barrage, picking up electronics in Eluru Road market, or heading home in Patamata, LocalTech brings verified repair service to your door in Vijayawada. Our technicians cross the Benz Circle grid faster than you'd expect.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "guntur",
    name: "Guntur",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Brodipet", "Arundelpet", "Nagarampalem", "Kothapet", "Amaravati Road", "Old Town", "Pattabhipuram", "Gorantla"],
    repairMarkets: ["Brodipet Electronics", "Old Town Market", "Amaravati Road Tech Street"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 18,
    reviewCount: 142,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Guntur's pepper and chilli trade built one of Andhra's most commercially active cities — and its professionals run on smartphones. LocalTech serves Brodipet's business hub and the residential quarters of Nagarampalem with same-day mobile repair at published prices.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "warangal",
    name: "Warangal",
    state: "Telangana",
    tier: "tier2",
    areas: ["Hanamkonda", "Kazipet", "NIT Warangal area", "Subedari", "Lashkar Bazaar", "Station Road", "Mulugu Road", "Balasamudram"],
    repairMarkets: ["Station Road Electronics", "Hanamkonda Market", "Subedari Tech Hub"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 17,
    reviewCount: 135,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Warangal's NIT and Kakatiya University bring in thousands of students who need fast, affordable repair. LocalTech bridges that gap — technicians in Hanamkonda and Kazipet with transparent pricing that students and working professionals alike can trust.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Balaji Nagar", "Renigunta Road", "SVIMS Area", "Tilak Road", "Leela Mahal Road", "SV University", "Alipiri", "K.T. Road"],
    repairMarkets: ["Balaji Nagar Electronics", "Car Street Market", "Tilak Road Tech Street"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 15,
    reviewCount: 125,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Tirupati is visited by millions each year, and locals and pilgrims alike need their devices to work — maps, UPI payments, and communication all depend on a functioning phone. LocalTech keeps Tirupati's residents connected with fast doorstep repair.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "nellore",
    name: "Nellore",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Grand Trunk Road", "Magunta Layout", "Pogathota", "Santhapet", "Auto Nagar", "Vedayapalem", "Akkayyapalem", "Balaji Nagar"],
    repairMarkets: ["Grand Trunk Road Electronics", "Santhapet Market", "Magunta Layout Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 16,
    reviewCount: 128,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Nellore's prawn and aquaculture industry keeps traders and exporters on the phone all day. LocalTech ensures that when your screen cracks or battery dies, a verified technician reaches your Grand Trunk Road office or Magunta Layout home quickly.",
    nearbyCity: "chennai",
  },
  {
    slug: "karimnagar",
    name: "Karimnagar",
    state: "Telangana",
    tier: "tier2",
    areas: ["Mankammathota", "Godavarikhani", "SR Nagar", "Vivekananda Nagar", "Jagtial Road", "AG Office Area", "Ramalayam", "Bypass Road"],
    repairMarkets: ["Mankammathota Electronics", "Main Road Market", "Jagtial Road Tech Street"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 14,
    reviewCount: 118,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Karimnagar has grown considerably since Telangana's formation, with new IT and government offices demanding reliable connectivity. LocalTech serves the city's growing middle class with verified doorstep repair from Mankammathota to the Jagtial Road corridor.",
    nearbyCity: "hyderabad",
  },
  {
    slug: "rajahmundry",
    name: "Rajahmundry",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Innespeta", "Suryaraopet", "Godavari Bund Road", "Morampudi", "Danavaipeta", "JC Colony", "One Town", "Kakinada Road"],
    repairMarkets: ["Innespeta Electronics", "Kakinada Road Market", "One Town Tech Hub"],
    priceIndex: 0.8,
    population: "5 lakh",
    techCount: 13,
    reviewCount: 112,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Rajahmundry sits on the Godavari delta, a cultural hub for East Godavari district. Its professionals and students in Danavaipeta and Innespeta now get access to metro-standard repair service through LocalTech — no compromise on quality in a smaller city.",
    nearbyCity: "vijayawada",
  },
  {
    slug: "kakinada",
    name: "Kakinada",
    state: "Andhra Pradesh",
    tier: "tier2",
    areas: ["Suryaraopet", "Rajamahendravaram Road", "JPN Road", "Gandhi Nagar", "Bhanugudi", "Ramaraopeta", "Main Road", "Back Road"],
    repairMarkets: ["Suryaraopet Market", "Main Road Electronics", "JPN Road Tech Street"],
    priceIndex: 0.8,
    population: "4 lakh",
    techCount: 12,
    reviewCount: 106,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Kakinada's deep-water port and petrochemical companies make it an economically active city despite its size. LocalTech brings professional mobile repair to your Suryaraopet home or Gandhi Nagar office without the uncertainty of local mobile repair shops.",
    nearbyCity: "rajahmundry",
  },
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Shahganj", "Fatehabad Road", "Civil Lines", "Sikandra", "Kamla Nagar", "Dayalbagh", "Tajganj", "Mantola"],
    repairMarkets: ["Sadar Bazaar Electronics", "Shahganj Market", "Civil Lines Tech Hub"],
    priceIndex: 0.8,
    population: "18 lakh",
    techCount: 22,
    reviewCount: 153,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Agra's tourism economy means millions of visitors passing through, and a large local workforce that depends on mobile banking, UPI, and logistics apps. LocalTech covers Civil Lines and Fatehabad Road with fast doorstep repair — as quick as a Taj selfie trip.",
    nearbyCity: "delhi",
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Lanka", "Sigra", "Sunderpur", "Kotwali", "Dashashwamedh", "BHU Campus", "Nadesar", "Orderly Bazaar"],
    repairMarkets: ["Lanka Electronics", "Sigra Market", "Godowlia Market"],
    priceIndex: 0.8,
    population: "18 lakh",
    techCount: 20,
    reviewCount: 148,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "BHU's massive campus and the commercial sprawl around Lanka and Sigra make Varanasi a city of contrasts — ancient ghats, busy markets, modern students. LocalTech brings modern repair standards to all of it, from BHU hostels to the silk-weaving lanes of Orderly Bazaar.",
    nearbyCity: "patna",
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    tier: "tier2",
    areas: ["Anna Nagar", "KK Nagar", "Alagar Kovil Road", "Bypass Road", "Tallakulam", "Simmakkal", "Palanganatham", "Thirunagar"],
    repairMarkets: ["Nethaji Road Electronics", "Town Hall Market", "Bypass Road Tech Street"],
    priceIndex: 0.8,
    population: "16 lakh",
    techCount: 20,
    reviewCount: 150,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Around Meenakshi Amman Temple, Madurai's bazaars have traded for 2,500 years. LocalTech brings a different kind of trust to this city — background-checked technicians with written warranties, serving KK Nagar and the growing Bypass Road corridor.",
    nearbyCity: "coimbatore",
  },
  {
    slug: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    tier: "tier2",
    areas: ["VV Mohalla", "Kuvempunagar", "Vijayanagar", "Gokulam", "Jayalakshmipuram", "Hebbal", "Srirampura", "Nanjangud Road"],
    repairMarkets: ["Sayyaji Rao Road Electronics", "Nazarbad Market", "Vijayanagar Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 18,
    reviewCount: 139,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Mysuru's heritage status and growing IT presence in Infosys and Wipro campuses have created a population that values quality and reliability. LocalTech matches that expectation — Gokulam to Hebbal covered with technicians who document every step.",
    nearbyCity: "bangalore",
  },
  {
    slug: "mangalore",
    name: "Mangalore",
    state: "Karnataka",
    tier: "tier2",
    areas: ["Hampankatta", "Falnir", "Kankanady", "Bejai", "Attavar", "Balmatta", "Urwa", "Deralakatte"],
    repairMarkets: ["Hampankatta Electronics", "Bunder Electronics Market", "Kankanady Tech Street"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 15,
    reviewCount: 120,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Mangalore's banking and port trade culture creates a workforce that genuinely relies on phones and laptops. From Hampankatta's commercial core to the residential lanes of Kankanady, LocalTech's verified technicians keep your devices running.",
    nearbyCity: "kochi",
  },
  {
    slug: "hubli",
    name: "Hubli",
    state: "Karnataka",
    tier: "tier2",
    areas: ["Keshwapur", "Vidyanagar", "Navanagar", "Dharwad", "Unkal", "Tarihal", "Gokul Road", "Hosur"],
    repairMarkets: ["Koppikar Road Electronics", "Station Road Market", "Vidyanagar Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 17,
    reviewCount: 129,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "The Hubli-Dharwad twin city is northern Karnataka's commercial engine. LocalTech covers both sides — from Gokul Road's new apartments to Keshwapur's trading community — with same-day repair and transparent pricing.",
    nearbyCity: "bangalore",
  },
  {
    slug: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Shastri Nagar", "Ratanada", "Paota", "Sardarpura", "Pal Road", "Chopasni Housing Board", "Mandore Road", "Bhati Circle"],
    repairMarkets: ["Clock Tower Market", "Sojati Gate Electronics", "Ratanada Tech Hub"],
    priceIndex: 0.8,
    population: "16 lakh",
    techCount: 19,
    reviewCount: 141,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "The Blue City's tourism industry and defence installations both create heavy device usage. LocalTech serves Jodhpur's Shastri Nagar professionals and Ratanada families with certified doorstep repair — without the guesswork of Clock Tower's repair lane.",
    nearbyCity: "jaipur",
  },
  {
    slug: "jabalpur",
    name: "Jabalpur",
    state: "Madhya Pradesh",
    tier: "tier2",
    areas: ["Napier Town", "Vijay Nagar", "Gorakhpur", "Gwarighat Road", "Adhartal", "Civil Lines", "Ranjhi", "Damoh Naka"],
    repairMarkets: ["Napier Town Electronics", "Medical Road Market", "Sadar Bazaar Tech Hub"],
    priceIndex: 0.8,
    population: "14 lakh",
    techCount: 18,
    reviewCount: 132,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Jabalpur's military cantonments and growing commercial areas around Vijay Nagar demand reliable devices. LocalTech brings a systematic approach to repair — verified credentials, documented work, 30-day warranty — to Napier Town and Civil Lines alike.",
    nearbyCity: "bhopal",
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    tier: "tier2",
    areas: ["Lawrence Road", "Ranjit Avenue", "Green Avenue", "Hall Bazaar", "GT Road", "Chheharta", "Majitha Road", "Batala Road"],
    repairMarkets: ["Lawrence Road Electronics", "Hall Bazaar Market", "Ranjit Avenue Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 17,
    reviewCount: 128,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Near the Golden Temple and the busy Golden Circle, Amritsar's tourism and trade economy keeps people moving fast. LocalTech ensures your phone isn't the bottleneck — verified repair at your Lawrence Road hotel or Ranjit Avenue home, same day.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "ludhiana",
    name: "Ludhiana",
    state: "Punjab",
    tier: "tier2",
    areas: ["Sarabha Nagar", "Model Town", "Dugri", "Civil Lines", "BRS Nagar", "Pakhowal Road", "GT Road", "Samrala Chowk"],
    repairMarkets: ["Clock Tower Electronics", "Chaura Bazaar Market", "Model Town Tech Hub"],
    priceIndex: 0.8,
    population: "17 lakh",
    techCount: 20,
    reviewCount: 147,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Ludhiana's hosiery and cycle industry is a 24/7 operation, and so is its need for working devices. From Sarabha Nagar's executive homes to the textile mills near GT Road, LocalTech provides fast mobile repair with no disruption to your workday.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "guwahati",
    name: "Guwahati",
    state: "Assam",
    tier: "tier2",
    areas: ["Dispur", "Pan Bazaar", "Paltan Bazaar", "Chandmari", "Noonmati", "Ganeshguri", "Six Mile", "Beltola"],
    repairMarkets: ["Pan Bazaar Electronics", "Paltan Bazaar Market", "Ganeshguri Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 16,
    reviewCount: 122,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "As Northeast India's commercial gateway, Guwahati's Pan Bazaar and Dispur government corridors see high device usage. LocalTech brings professional mobile repair to a market that has historically been underserved — from Chandmari to Six Mile.",
    nearbyCity: "kolkata",
  },
  {
    slug: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    tier: "tier2",
    areas: ["Saheed Nagar", "Nayapalli", "Patia", "Khandagiri", "Bharatpur", "Jaydev Vihar", "Chandrasekharpur", "Tamando"],
    repairMarkets: ["Janpath Market Electronics", "Saheed Nagar Market", "Patia Tech Street"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 17,
    reviewCount: 127,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Bhubaneswar's IT sector in Infocity and the government offices around Nayapalli have transformed the city's device landscape. LocalTech matches that growth with certified technicians who serve Saheed Nagar and Jaydev Vihar with fast, warrantied repair.",
    nearbyCity: "kolkata",
  },
  {
    slug: "thiruvananthapuram",
    name: "Thiruvananthapuram",
    state: "Kerala",
    tier: "tier2",
    areas: ["Technopark", "Pattom", "Kowdiar", "Thampanoor", "Karamana", "Vanchiyoor", "Kesavadasapuram", "Ulloor"],
    repairMarkets: ["MG Road Electronics", "Chalai Market", "East Fort Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 18,
    reviewCount: 133,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Kerala's capital has Technopark — one of Asia's largest IT parks — producing a tech-savvy population with high device standards. LocalTech covers the Technopark campuses and Pattom's residential areas with certified repair that matches what IT professionals expect.",
    nearbyCity: "kochi",
  },
  {
    slug: "kozhikode",
    name: "Kozhikode",
    state: "Kerala",
    tier: "tier2",
    areas: ["Calicut Beach", "Medical College", "Palayam", "Mavoor Road", "Chevayur", "Arayidathupalam", "Nadakkavu", "Meenchanda"],
    repairMarkets: ["SM Street Electronics", "Palayam Market", "Big Bazaar Road Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 15,
    reviewCount: 118,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Kozhikode's IT startups and Gulf returnee economy drive strong smartphone usage — and high expectations. LocalTech brings the same trust to SM Street's repair market by putting verified, insured technicians at your Palayam doorstep.",
    nearbyCity: "kochi",
  },
  {
    slug: "nashik",
    name: "Nashik",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Gangapur Road", "College Road", "CIDCO", "Satpur", "Deolali", "Nashik Road", "Panchavati", "Trimbak Road"],
    repairMarkets: ["College Road Electronics", "Mahatma Gandhi Road Market", "CIDCO Tech Hub"],
    priceIndex: 0.8,
    population: "15 lakh",
    techCount: 19,
    reviewCount: 138,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Nashik's wine country reputation belies a serious manufacturing and tech base — defence industries at Deolali and Gangapur Road's growing residential zones both need reliable device repair. LocalTech covers all of Nashik with same-day service.",
    nearbyCity: "pune",
  },
  {
    slug: "aurangabad",
    name: "Aurangabad",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Cidco", "Garkheda", "Rauza Bagh", "Osmanpura", "Waluj", "Gulmandi", "Kranti Chowk", "Jalna Road"],
    repairMarkets: ["Gulmandi Electronics", "Kranti Chowk Market", "Jalna Road Tech Hub"],
    priceIndex: 0.8,
    population: "13 lakh",
    techCount: 17,
    reviewCount: 127,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Near the Bibi Ka Maqbara and the Ajanta-Ellora tourism belt, Aurangabad's industrial zones in Waluj and Cidco create a population that works hard and needs devices that match. LocalTech brings certified repair to your door anywhere in the city.",
    nearbyCity: "pune",
  },
  {
    slug: "solapur",
    name: "Solapur",
    state: "Maharashtra",
    tier: "tier2",
    areas: ["Vijay Nagar", "Murarji Peth", "Kamgar Nagar", "Station Road", "Hotgi Road", "Akkalkot Road", "Budhwar Peth", "Shegaon Road"],
    repairMarkets: ["Station Road Electronics", "Budhwar Peth Market", "Vijay Nagar Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 118,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Solapur's textile mills and educational institutions generate steady device usage across Vijay Nagar and the old town. LocalTech makes repair straightforward here — a verified technician to your address, a written quote, and a warranty certificate on completion.",
    nearbyCity: "pune",
  },
  {
    slug: "dehradun",
    name: "Dehradun",
    state: "Uttarakhand",
    tier: "tier2",
    areas: ["Rajpur Road", "Patel Nagar", "Vasant Vihar", "Dalanwala", "Raipur", "Clement Town", "Ballupur", "Sahastradhara Road"],
    repairMarkets: ["Paltan Bazaar Electronics", "Rajpur Road Market", "Clock Tower Tech Hub"],
    priceIndex: 0.8,
    population: "8 lakh",
    techCount: 15,
    reviewCount: 115,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Dehradun's school-city reputation and growing IT presence along Rajpur Road make it a city where residents expect good service. LocalTech covers the hill city's spread — from Clock Tower to Sahastradhara Road — with verified mobile repair.",
    nearbyCity: "delhi",
  },
  {
    slug: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    tier: "tier2",
    areas: ["The Mall", "Cart Road", "Lower Bazaar", "Chhota Shimla", "Vikasnagar", "Sanjauli", "Tara Devi", "Chail Road"],
    repairMarkets: ["The Mall Road Electronics", "Lower Bazaar Market", "Lakkar Bazaar Tech Hub"],
    priceIndex: 0.8,
    population: "3 lakh",
    techCount: 10,
    reviewCount: 96,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "Shimla's steep hillsides mean a broken phone on the Mall Road is a real problem — there are few local options and the tourist season keeps repair shops overwhelmed. LocalTech brings a certified technician to your hotel or apartment, no trek to Lower Bazaar needed.",
    nearbyCity: "chandigarh",
  },
  {
    slug: "ajmer",
    name: "Ajmer",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Vaishali Nagar", "Nasirabad Road", "Madar Gate", "Nala Bazaar", "Civil Lines", "Pushkar Road", "Ana Sagar", "Ramganj Mandi"],
    repairMarkets: ["Station Road Electronics", "Nala Bazaar Market", "Madar Gate Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 13,
    reviewCount: 106,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Ajmer's dargah tourism and Pushkar's fair season create a city in constant motion. LocalTech's Ajmer technicians serve Civil Lines residents and the busy Vaishali Nagar area with quick, certified repair — so pilgrims and locals alike stay connected.",
    nearbyCity: "jaipur",
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    tier: "tier2",
    areas: ["Hiran Magri", "Sector 4", "Udaipole", "Sukhadia Circle", "Fatehpura", "Bedla", "Madhuban", "Chetak Circle"],
    repairMarkets: ["Bada Bazaar Electronics", "Sukhadia Circle Market", "Chetak Circle Tech Hub"],
    priceIndex: 0.8,
    population: "6 lakh",
    techCount: 13,
    reviewCount: 108,
    avgRating: 4.7,
    responseMinutes: "45–60",
    localIntro: "The City of Lakes draws tourists and new residents in equal measure, but mobile repair options haven't kept pace. LocalTech covers Hiran Magri and Sector 4 with certified technicians — so residents of India's most scenic city don't lose sleep over a cracked screen.",
    nearbyCity: "jaipur",
  },
  {
    slug: "meerut",
    name: "Meerut",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Shastri Nagar", "Kanker Khera", "Pallavpuram", "Civil Lines", "Hapur Road", "Modipuram", "Begumpul", "Brahmpuri"],
    repairMarkets: ["Ghantaghar Market", "Civil Lines Electronics", "Hapur Road Tech Hub"],
    priceIndex: 0.8,
    population: "14 lakh",
    techCount: 18,
    reviewCount: 131,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Meerut's sports manufacturing and rising IT campuses make it a city punching above its tier. LocalTech brings professional repair to Civil Lines offices and Pallavpuram homes — with the kind of service quality that the city's newer generation demands.",
    nearbyCity: "delhi",
  },
  {
    slug: "aligarh",
    name: "Aligarh",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Ramghat Road", "Marris Road", "Medical Road", "Jamalpur", "Quarsi", "Civil Lines", "Dhanipur", "Sasni Gate"],
    repairMarkets: ["Upper Kot Market", "Civil Lines Electronics", "Medical Road Tech Hub"],
    priceIndex: 0.8,
    population: "9 lakh",
    techCount: 14,
    reviewCount: 112,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "AMU's massive campus and Aligarh's lock-manufacturing legacy both contribute to a city with strong device usage. LocalTech serves the university area and the Marris Road commercial corridor with verified repair — no Ramghat Road bargaining needed.",
    nearbyCity: "agra",
  },
  {
    slug: "bareilly",
    name: "Bareilly",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Subhash Nagar", "CB Ganj", "Pilibhit Road", "Nainital Road", "Rampur Garden", "Izzatnagar", "Badaun Road"],
    repairMarkets: ["Civil Lines Market", "Subhash Nagar Electronics", "Station Road Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 116,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Bareilly's furniture and steel industries and its role as the Rohilkhand division headquarters make it a commercially active city. LocalTech covers Civil Lines to CB Ganj with certified repair — your device gets a written estimate before work starts, every time.",
    nearbyCity: "delhi",
  },
  {
    slug: "moradabad",
    name: "Moradabad",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Brahmpuri", "Majhola", "Katghar", "Buddhi Vihar", "Pakwara", "Kanth Road", "Delhi Road"],
    repairMarkets: ["Brass Market Electronics", "Civil Lines Market", "Delhi Road Tech Hub"],
    priceIndex: 0.8,
    population: "9 lakh",
    techCount: 14,
    reviewCount: 110,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Moradabad's brass export industry keeps traders constantly in touch with buyers worldwide — a dead phone is a business problem. LocalTech covers Civil Lines and the Majhola residential areas with fast, certified repair that you don't have to negotiate for.",
    nearbyCity: "delhi",
  },
  {
    slug: "gorakhpur",
    name: "Gorakhpur",
    state: "Uttar Pradesh",
    tier: "tier2",
    areas: ["Civil Lines", "Golghar", "Padrauna Road", "Taramandal", "Betiahata", "Basharatpur", "Medical College Road", "Bank Road"],
    repairMarkets: ["Golghar Market", "Civil Lines Electronics", "Medical College Road Tech Hub"],
    priceIndex: 0.8,
    population: "10 lakh",
    techCount: 15,
    reviewCount: 114,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Gorakhpur, home to the Gorakhnath temple and a major railway junction, has a large mobile-using population in Civil Lines and Golghar. LocalTech brings certified repair here — technicians who come to your Betiahata home or Bank Road office.",
    nearbyCity: "varanasi",
  },
  {
    slug: "dhanbad",
    name: "Dhanbad",
    state: "Jharkhand",
    tier: "tier2",
    areas: ["Hirapur", "Jharia", "Katras", "Bank More", "Saraidhela", "Sindri", "Bhuli", "Govindpur"],
    repairMarkets: ["Bank More Electronics", "Saraidhela Market", "Hirapur Tech Hub"],
    priceIndex: 0.8,
    population: "12 lakh",
    techCount: 16,
    reviewCount: 120,
    avgRating: 4.6,
    responseMinutes: "45–60",
    localIntro: "Dhanbad's coal mines and IIT(ISM) campus create a unique mix of industrial workers and top-tier students with high device dependency. LocalTech covers Bank More and Hirapur with verified repair service — consistent quality whether you're in a mine-office or a campus hostel.",
    nearbyCity: "ranchi",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}
